// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_webhook.sql

package model

import (
	"context"
)

const deleteBotWebhook = `-- name: DeleteBotWebhook :execrows
DELETE FROM bot_webhooks WHERE bot_user_id = $1
`

func (q *Queries) DeleteBotWebhook(ctx context.Context, botUserID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBotWebhook, botUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotWebhook = `-- name: GetBotWebhook :one
SELECT bot_user_id, url, secret_hash, events, enabled, created_at, updated_at
FROM bot_webhooks
WHERE bot_user_id = $1
`

func (q *Queries) GetBotWebhook(ctx context.Context, botUserID int64) (BotWebhook, error) {
	row := q.db.QueryRow(ctx, getBotWebhook, botUserID)
	var i BotWebhook
	err := row.Scan(
		&i.BotUserID,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBotWebhooksForConversation = `-- name: ListActiveBotWebhooksForConversation :many
SELECT bw.bot_user_id,
       bw.url,
       bw.secret_hash,
       bw.events,
       bw.enabled,
       bw.created_at,
       bw.updated_at
FROM bot_webhooks bw
JOIN conversation_members cm ON cm.user_id = bw.bot_user_id
JOIN user_info ui ON ui.id = bw.bot_user_id
WHERE cm.conversation_id = $1
  AND bw.enabled = TRUE
  AND ui.user_type = 'bot'
  AND ui.status = 1
`

// Returns enabled webhooks for bots that are members of the given conversation.
// Used by the BotWebhookConsumer to fan out message.created events.
func (q *Queries) ListActiveBotWebhooksForConversation(ctx context.Context, conversationID int64) ([]BotWebhook, error) {
	rows, err := q.db.Query(ctx, listActiveBotWebhooksForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotWebhook{}
	for rows.Next() {
		var i BotWebhook
		if err := rows.Scan(
			&i.BotUserID,
			&i.Url,
			&i.SecretHash,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotWebhook = `-- name: UpsertBotWebhook :one
INSERT INTO bot_webhooks (bot_user_id, url, secret_hash, events, enabled, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (bot_user_id) DO UPDATE SET
    url = EXCLUDED.url,
    secret_hash = EXCLUDED.secret_hash,
    events = EXCLUDED.events,
    enabled = EXCLUDED.enabled,
    updated_at = NOW()
RETURNING bot_user_id, url, secret_hash, events, enabled, created_at, updated_at
`

type UpsertBotWebhookParams struct {
	BotUserID  int64    `json:"bot_user_id"`
	Url        string   `json:"url"`
	SecretHash string   `json:"secret_hash"`
	Events     []string `json:"events"`
	Enabled    bool     `json:"enabled"`
}

func (q *Queries) UpsertBotWebhook(ctx context.Context, arg UpsertBotWebhookParams) (BotWebhook, error) {
	row := q.db.QueryRow(ctx, upsertBotWebhook,
		arg.BotUserID,
		arg.Url,
		arg.SecretHash,
		arg.Events,
		arg.Enabled,
	)
	var i BotWebhook
	err := row.Scan(
		&i.BotUserID,
		&i.Url,
		&i.SecretHash,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
