// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_token.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBotToken = `-- name: CreateBotToken :one
INSERT INTO bot_tokens (id, bot_user_id, token_hash, name, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, bot_user_id, token_hash, name, scopes, expires_at, revoked_at, created_at
`

type CreateBotTokenParams struct {
	ID        int64              `json:"id"`
	BotUserID int64              `json:"bot_user_id"`
	TokenHash string             `json:"token_hash"`
	Name      string             `json:"name"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateBotToken(ctx context.Context, arg CreateBotTokenParams) (BotToken, error) {
	row := q.db.QueryRow(ctx, createBotToken,
		arg.ID,
		arg.BotUserID,
		arg.TokenHash,
		arg.Name,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i BotToken
	err := row.Scan(
		&i.ID,
		&i.BotUserID,
		&i.TokenHash,
		&i.Name,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBotTokenByHash = `-- name: GetBotTokenByHash :one
SELECT bt.id,
       bt.bot_user_id,
       bt.token_hash,
       bt.name,
       bt.scopes,
       bt.expires_at,
       bt.revoked_at,
       bt.created_at,
       ui.user_type,
       ui.status AS user_status,
       ui.nickname,
       ui.avatar
FROM bot_tokens bt
JOIN user_info ui ON ui.id = bt.bot_user_id
WHERE bt.token_hash = $1
`

type GetBotTokenByHashRow struct {
	ID         int64              `json:"id"`
	BotUserID  int64              `json:"bot_user_id"`
	TokenHash  string             `json:"token_hash"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserType   string             `json:"user_type"`
	UserStatus int16              `json:"user_status"`
	Nickname   string             `json:"nickname"`
	Avatar     string             `json:"avatar"`
}

// Returns the token entry plus the owner's user_type / status / nickname so
// the BotAuth middleware can validate the bot identity in a single query.
func (q *Queries) GetBotTokenByHash(ctx context.Context, tokenHash string) (GetBotTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getBotTokenByHash, tokenHash)
	var i GetBotTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.BotUserID,
		&i.TokenHash,
		&i.Name,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserType,
		&i.UserStatus,
		&i.Nickname,
		&i.Avatar,
	)
	return i, err
}

const listBotTokensByBot = `-- name: ListBotTokensByBot :many
SELECT id, bot_user_id, token_hash, name, scopes, expires_at, revoked_at, created_at
FROM bot_tokens
WHERE bot_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBotTokensByBot(ctx context.Context, botUserID int64) ([]BotToken, error) {
	rows, err := q.db.Query(ctx, listBotTokensByBot, botUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotToken{}
	for rows.Next() {
		var i BotToken
		if err := rows.Scan(
			&i.ID,
			&i.BotUserID,
			&i.TokenHash,
			&i.Name,
			&i.Scopes,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBotToken = `-- name: RevokeBotToken :execrows
UPDATE bot_tokens
SET revoked_at = NOW()
WHERE id = $1 AND bot_user_id = $2 AND revoked_at IS NULL
`

type RevokeBotTokenParams struct {
	ID        int64 `json:"id"`
	BotUserID int64 `json:"bot_user_id"`
}

func (q *Queries) RevokeBotToken(ctx context.Context, arg RevokeBotTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBotToken, arg.ID, arg.BotUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
