// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package model

import (
	"context"
)

const addConversationMembers = `-- name: AddConversationMembers :execrows
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
`

type AddConversationMembersParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) AddConversationMembers(ctx context.Context, arg AddConversationMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, addConversationMembers, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, conversation_type, is_active)
VALUES ($1, $2, true)
RETURNING id, conversation_type, is_active, created_at
`

type CreateConversationParams struct {
	ID               int64  `json:"id"`
	ConversationType string `json:"conversation_type"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ID, arg.ConversationType)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ConversationType,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, conversation_type, is_active, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ConversationType,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT conversation_id, user_id, is_muted, muted_until, joined_at
FROM conversation_members
WHERE conversation_id = $1
`

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID int64) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMember{}
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.IsMuted,
			&i.MutedUntil,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT c.id, c.conversation_type, c.is_active, c.created_at
FROM conversations c
INNER JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, userID int64) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getConversationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ConversationType,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
