// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friendship.sql

package model

import (
	"context"
)

const getFriendship = `-- name: GetFriendship :one
SELECT user_id, friend_id, status
FROM friendships
WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

type GetFriendshipRow struct {
	UserID   int64  `json:"user_id"`
	FriendID int64  `json:"friend_id"`
	Status   string `json:"status"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (GetFriendshipRow, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i GetFriendshipRow
	err := row.Scan(&i.UserID, &i.FriendID, &i.Status)
	return i, err
}

const getFriendshipBidirectional = `-- name: GetFriendshipBidirectional :many
SELECT user_id, friend_id, status
FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type GetFriendshipBidirectionalParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

type GetFriendshipBidirectionalRow struct {
	UserID   int64  `json:"user_id"`
	FriendID int64  `json:"friend_id"`
	Status   string `json:"status"`
}

func (q *Queries) GetFriendshipBidirectional(ctx context.Context, arg GetFriendshipBidirectionalParams) ([]GetFriendshipBidirectionalRow, error) {
	rows, err := q.db.Query(ctx, getFriendshipBidirectional, arg.UserID, arg.FriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendshipBidirectionalRow{}
	for rows.Next() {
		var i GetFriendshipBidirectionalRow
		if err := rows.Scan(&i.UserID, &i.FriendID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendshipByPair = `-- name: GetFriendshipByPair :one
SELECT user_id, friend_id, status, created_at, updated_at
FROM friendships
WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipByPairParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByPair, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT user_id, friend_id, status, created_at, updated_at
FROM friendships
WHERE user_id = $1 AND status = 'accepted'
ORDER BY created_at DESC
`

func (q *Queries) ListFriends(ctx context.Context, userID int64) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFriendApplications = `-- name: ListPendingFriendApplications :many
SELECT user_id, friend_id, status, created_at, updated_at
FROM friendships
WHERE friend_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingFriendApplications(ctx context.Context, friendID int64) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listPendingFriendApplications, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFriendship = `-- name: UpsertFriendship :one
INSERT INTO friendships (user_id, friend_id, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (user_id, friend_id) DO UPDATE SET
    status = EXCLUDED.status,
    updated_at = NOW()
RETURNING user_id, friend_id, status, created_at, updated_at
`

type UpsertFriendshipParams struct {
	UserID   int64  `json:"user_id"`
	FriendID int64  `json:"friend_id"`
	Status   string `json:"status"`
}

func (q *Queries) UpsertFriendship(ctx context.Context, arg UpsertFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, upsertFriendship, arg.UserID, arg.FriendID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
