// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesByConversation = `-- name: CountMessagesByConversation :one
SELECT COUNT(*) FROM messages WHERE conversation_id = $1
`

func (q *Queries) CountMessagesByConversation(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByConversation, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, conversation_id, sender_id, message_type, content, client_msg_id, mentions, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type InsertMessageParams struct {
	ID             int64   `json:"id"`
	ConversationID int64   `json:"conversation_id"`
	SenderID       int64   `json:"sender_id"`
	MessageType    string  `json:"message_type"`
	Content        []byte  `json:"content"`
	ClientMsgID    *string `json:"client_msg_id"`
	Mentions       []byte  `json:"mentions"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.MessageType,
		arg.Content,
		arg.ClientMsgID,
		arg.Mentions,
	)
	return err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, sender_id, message_type, content, client_msg_id, mentions, created_at
FROM messages
WHERE conversation_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMessagesByConversationParams struct {
	ConversationID int64              `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ID             int64              `json:"id"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation,
		arg.ConversationID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MessageType,
			&i.Content,
			&i.ClientMsgID,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversationInitial = `-- name: ListMessagesByConversationInitial :many
SELECT id, conversation_id, sender_id, message_type, content, client_msg_id, mentions, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListMessagesByConversationInitialParams struct {
	ConversationID int64 `json:"conversation_id"`
	Limit          int32 `json:"limit"`
}

func (q *Queries) ListMessagesByConversationInitial(ctx context.Context, arg ListMessagesByConversationInitialParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversationInitial, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MessageType,
			&i.Content,
			&i.ClientMsgID,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
