// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOutboxRecordsBefore = `-- name: DeleteOutboxRecordsBefore :execrows
DELETE FROM outbox_records
WHERE processed_at IS NOT NULL AND processed_at < $1
`

func (q *Queries) DeleteOutboxRecordsBefore(ctx context.Context, processedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboxRecordsBefore, processedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchPendingOutboxRecords = `-- name: FetchPendingOutboxRecords :many
SELECT id, topic, key, payload, created_at
FROM outbox_records
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT $1
`

type FetchPendingOutboxRecordsRow struct {
	ID        int64              `json:"id"`
	Topic     string             `json:"topic"`
	Key       string             `json:"key"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FetchPendingOutboxRecords(ctx context.Context, limit int32) ([]FetchPendingOutboxRecordsRow, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutboxRecords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchPendingOutboxRecordsRow{}
	for rows.Next() {
		var i FetchPendingOutboxRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxRecord = `-- name: InsertOutboxRecord :one
INSERT INTO outbox_records (topic, key, payload)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertOutboxRecordParams struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxRecord(ctx context.Context, arg InsertOutboxRecordParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutboxRecord, arg.Topic, arg.Key, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markOutboxRecordsProcessed = `-- name: MarkOutboxRecordsProcessed :execrows
UPDATE outbox_records
SET processed_at = NOW()
WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) MarkOutboxRecordsProcessed(ctx context.Context, dollar_1 []int64) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxRecordsProcessed, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
