// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddConversationMemberWithRole(ctx context.Context, arg AddConversationMemberWithRoleParams) (int64, error)
	AddConversationMembers(ctx context.Context, arg AddConversationMembersParams) (int64, error)
	ClearBotTokenActions(ctx context.Context, tokenID int64) (int64, error)
	CountMessagesByConversation(ctx context.Context, conversationID int64) (int64, error)
	CreateBotToken(ctx context.Context, arg CreateBotTokenParams) (BotToken, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error)
	CreateFriendTag(ctx context.Context, arg CreateFriendTagParams) (FriendTag, error)
	CreateUserBotOwnership(ctx context.Context, arg CreateUserBotOwnershipParams) (UserBot, error)
	CreateUserBotProfile(ctx context.Context, arg CreateUserBotProfileParams) (UserInfo, error)
	CreateUserInfo(ctx context.Context, arg CreateUserInfoParams) (UserInfo, error)
	DeactivateConversation(ctx context.Context, id int64) error
	DeleteBotWebhook(ctx context.Context, botUserID int64) (int64, error)
	DeleteFriendTag(ctx context.Context, arg DeleteFriendTagParams) (int64, error)
	DeleteOutboxRecordsBefore(ctx context.Context, processedAt pgtype.Timestamptz) (int64, error)
	FetchPendingOutboxRecords(ctx context.Context, limit int32) ([]FetchPendingOutboxRecordsRow, error)
	GetBotActionByName(ctx context.Context, action string) (BotAction, error)
	// Returns the token entry plus the owner's user_type / status / nickname so
	// the BotAuth middleware can validate the bot identity in a single query.
	GetBotTokenByHash(ctx context.Context, tokenHash string) (GetBotTokenByHashRow, error)
	GetBotWebhook(ctx context.Context, botUserID int64) (BotWebhook, error)
	GetConversation(ctx context.Context, id int64) (GetConversationRow, error)
	GetConversationCreator(ctx context.Context, id int64) (int64, error)
	GetConversationMembers(ctx context.Context, conversationID int64) ([]GetConversationMembersRow, error)
	GetConversationMembersDetail(ctx context.Context, conversationID int64) ([]GetConversationMembersDetailRow, error)
	GetConversationReadState(ctx context.Context, arg GetConversationReadStateParams) (ConversationReadState, error)
	GetConversationsByUserID(ctx context.Context, userID int64) ([]GetConversationsByUserIDRow, error)
	GetDirectConversationByMembers(ctx context.Context, arg GetDirectConversationByMembersParams) (GetDirectConversationByMembersRow, error)
	GetEnabledActionByWebhookEvent(ctx context.Context, event string) (string, error)
	GetFriendTagByID(ctx context.Context, arg GetFriendTagByIDParams) (FriendTag, error)
	GetFriendTagsByIDs(ctx context.Context, arg GetFriendTagsByIDsParams) ([]FriendTag, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (GetFriendshipRow, error)
	GetFriendshipBidirectional(ctx context.Context, arg GetFriendshipBidirectionalParams) ([]GetFriendshipBidirectionalRow, error)
	GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error)
	GetManagedBotToken(ctx context.Context, arg GetManagedBotTokenParams) (BotToken, error)
	GetManagedUserBot(ctx context.Context, arg GetManagedUserBotParams) (GetManagedUserBotRow, error)
	GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error)
	GetUserInfoByEmail(ctx context.Context, email string) (UserInfo, error)
	GetUserInfoByID(ctx context.Context, id int64) (UserInfo, error)
	GetUserInfoByNickname(ctx context.Context, nickname string) (UserInfo, error)
	GetUserType(ctx context.Context, id int64) (string, error)
	GrantBotTokenAction(ctx context.Context, arg GrantBotTokenActionParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	InsertOutboxRecord(ctx context.Context, arg InsertOutboxRecordParams) (int64, error)
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	IsMemberMuted(ctx context.Context, arg IsMemberMutedParams) (IsMemberMutedRow, error)
	// Returns enabled webhooks for bots that are members of the given conversation.
	// Used by the BotWebhookConsumer to fan out message.created events.
	ListActiveBotWebhooksForConversation(ctx context.Context, conversationID int64) ([]BotWebhook, error)
	ListBotTokensByBot(ctx context.Context, botUserID int64) ([]BotToken, error)
	ListConversationReadStates(ctx context.Context, conversationID int64) ([]ConversationReadState, error)
	ListEnabledActionsByToken(ctx context.Context, tokenID int64) ([]string, error)
	ListEnabledBotActions(ctx context.Context) ([]BotAction, error)
	ListEnabledBotActionsByNames(ctx context.Context, dollar_1 []string) ([]BotAction, error)
	ListEnabledBotEvents(ctx context.Context) ([]ListEnabledBotEventsRow, error)
	ListFriendTagAssignmentsForUser(ctx context.Context, userID int64) ([]ListFriendTagAssignmentsForUserRow, error)
	ListFriendTags(ctx context.Context, userID int64) ([]FriendTag, error)
	ListFriendTagsForFriend(ctx context.Context, arg ListFriendTagsForFriendParams) ([]FriendTag, error)
	ListFriends(ctx context.Context, dollar_1 int64) ([]ListFriendsRow, error)
	ListFriendsByTagID(ctx context.Context, arg ListFriendsByTagIDParams) ([]ListFriendsByTagIDRow, error)
	ListFriendsByTagName(ctx context.Context, arg ListFriendsByTagNameParams) ([]ListFriendsByTagNameRow, error)
	ListManagedUserBots(ctx context.Context, ownerUserID int64) ([]ListManagedUserBotsRow, error)
	ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]Message, error)
	ListMessagesByConversationInitial(ctx context.Context, arg ListMessagesByConversationInitialParams) ([]Message, error)
	ListPendingFriendApplications(ctx context.Context, friendID int64) ([]Friendship, error)
	MarkOutboxRecordsProcessed(ctx context.Context, dollar_1 []int64) (int64, error)
	RemoveConversationMembers(ctx context.Context, arg RemoveConversationMembersParams) (int64, error)
	RemoveFriendTagAssignment(ctx context.Context, arg RemoveFriendTagAssignmentParams) (int64, error)
	RenameFriendTag(ctx context.Context, arg RenameFriendTagParams) (FriendTag, error)
	ReplaceFriendTags(ctx context.Context, arg ReplaceFriendTagsParams) error
	RevokeAllBotTokensByBot(ctx context.Context, botUserID int64) (int64, error)
	RevokeBotToken(ctx context.Context, arg RevokeBotTokenParams) (int64, error)
	RevokeManagedBotToken(ctx context.Context, arg RevokeManagedBotTokenParams) (int64, error)
	SearchConversationsByName(ctx context.Context, arg SearchConversationsByNameParams) ([]SearchConversationsByNameRow, error)
	SearchFriendsByQuery(ctx context.Context, arg SearchFriendsByQueryParams) ([]SearchFriendsByQueryRow, error)
	SearchMessagesGlobal(ctx context.Context, arg SearchMessagesGlobalParams) ([]SearchMessagesGlobalRow, error)
	SearchMessagesInConversation(ctx context.Context, arg SearchMessagesInConversationParams) ([]SearchMessagesInConversationRow, error)
	SearchUserInfoByNickname(ctx context.Context, arg SearchUserInfoByNicknameParams) ([]UserInfo, error)
	SearchUserInfoByQuery(ctx context.Context, arg SearchUserInfoByQueryParams) ([]SearchUserInfoByQueryRow, error)
	SoftDeleteManagedUserBot(ctx context.Context, arg SoftDeleteManagedUserBotParams) (int64, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) error
	UpdateConversationCreator(ctx context.Context, arg UpdateConversationCreatorParams) error
	UpdateConversationMemberRole(ctx context.Context, arg UpdateConversationMemberRoleParams) (int64, error)
	UpdateManagedBotToken(ctx context.Context, arg UpdateManagedBotTokenParams) (BotToken, error)
	UpdateManagedUserBotProfile(ctx context.Context, arg UpdateManagedUserBotProfileParams) (UserInfo, error)
	UpdateManagedUserBotStatus(ctx context.Context, arg UpdateManagedUserBotStatusParams) (UserInfo, error)
	UpdateUserInfoProfile(ctx context.Context, arg UpdateUserInfoProfileParams) (UserInfo, error)
	UpdateUserInfoStatus(ctx context.Context, arg UpdateUserInfoStatusParams) (UserInfo, error)
	UpdateUserInfoType(ctx context.Context, arg UpdateUserInfoTypeParams) (int64, error)
	UpsertBotWebhook(ctx context.Context, arg UpsertBotWebhookParams) (BotWebhook, error)
	UpsertConversationReadState(ctx context.Context, arg UpsertConversationReadStateParams) (ConversationReadState, error)
	UpsertFriendship(ctx context.Context, arg UpsertFriendshipParams) (Friendship, error)
}

var _ Querier = (*Queries)(nil)
