// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_state.sql

package model

import (
	"context"
)

const getConversationReadState = `-- name: GetConversationReadState :one
SELECT conversation_id, user_id, last_read_message_id, updated_at
FROM conversation_read_states
WHERE conversation_id = $1 AND user_id = $2
`

type GetConversationReadStateParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) GetConversationReadState(ctx context.Context, arg GetConversationReadStateParams) (ConversationReadState, error) {
	row := q.db.QueryRow(ctx, getConversationReadState, arg.ConversationID, arg.UserID)
	var i ConversationReadState
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationReadStates = `-- name: ListConversationReadStates :many
SELECT conversation_id, user_id, last_read_message_id, updated_at
FROM conversation_read_states
WHERE conversation_id = $1
ORDER BY user_id
`

func (q *Queries) ListConversationReadStates(ctx context.Context, conversationID int64) ([]ConversationReadState, error) {
	rows, err := q.db.Query(ctx, listConversationReadStates, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationReadState{}
	for rows.Next() {
		var i ConversationReadState
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.LastReadMessageID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversationReadState = `-- name: UpsertConversationReadState :one
INSERT INTO conversation_read_states (conversation_id, user_id, last_read_message_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (conversation_id, user_id)
DO UPDATE SET
    last_read_message_id = GREATEST(conversation_read_states.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at = CASE
        WHEN EXCLUDED.last_read_message_id > conversation_read_states.last_read_message_id THEN NOW()
        ELSE conversation_read_states.updated_at
    END
RETURNING conversation_id, user_id, last_read_message_id, updated_at
`

type UpsertConversationReadStateParams struct {
	ConversationID    int64 `json:"conversation_id"`
	UserID            int64 `json:"user_id"`
	LastReadMessageID int64 `json:"last_read_message_id"`
}

func (q *Queries) UpsertConversationReadState(ctx context.Context, arg UpsertConversationReadStateParams) (ConversationReadState, error) {
	row := q.db.QueryRow(ctx, upsertConversationReadState, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	var i ConversationReadState
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.UpdatedAt,
	)
	return i, err
}
