// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package server

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/internal/logic/friendshipservice"
	"github.com/hellopoisonx/aim/app/logic/rpc/internal/svc"
	"github.com/hellopoisonx/aim/app/logic/rpc/pb"
)

type FriendshipServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFriendshipServiceServer
}

func NewFriendshipServiceServer(svcCtx *svc.ServiceContext) *FriendshipServiceServer {
	return &FriendshipServiceServer{
		svcCtx: svcCtx,
	}
}

// AddFriend sends a friend request or accepts an existing pending one.
func (s *FriendshipServiceServer) AddFriend(ctx context.Context, in *pb.AddFriendReq) (*pb.AddFriendResp, error) {
	l := friendshipservicelogic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

// ListFriendApplications lists pending friend applications received by the user.
func (s *FriendshipServiceServer) ListFriendApplications(ctx context.Context, in *pb.ListFriendApplicationsReq) (*pb.ListFriendApplicationsResp, error) {
	l := friendshipservicelogic.NewListFriendApplicationsLogic(ctx, s.svcCtx)
	return l.ListFriendApplications(in)
}

// AcceptFriend accepts a pending friend request.
func (s *FriendshipServiceServer) AcceptFriend(ctx context.Context, in *pb.AcceptFriendReq) (*pb.AcceptFriendResp, error) {
	l := friendshipservicelogic.NewAcceptFriendLogic(ctx, s.svcCtx)
	return l.AcceptFriend(in)
}

// RejectFriend rejects a pending friend request.
func (s *FriendshipServiceServer) RejectFriend(ctx context.Context, in *pb.RejectFriendReq) (*pb.RejectFriendResp, error) {
	l := friendshipservicelogic.NewRejectFriendLogic(ctx, s.svcCtx)
	return l.RejectFriend(in)
}
