// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package botservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserBotToConversationReq         = pb.AddUserBotToConversationReq
	AddUserBotToConversationResp        = pb.AddUserBotToConversationResp
	CreateUserBotDirectConversationReq  = pb.CreateUserBotDirectConversationReq
	CreateUserBotDirectConversationResp = pb.CreateUserBotDirectConversationResp
	CreateUserBotReq                    = pb.CreateUserBotReq
	CreateUserBotResp                   = pb.CreateUserBotResp
	CreateUserBotTokenReq               = pb.CreateUserBotTokenReq
	CreateUserBotTokenResp              = pb.CreateUserBotTokenResp
	DeleteBotWebhookReq                 = pb.DeleteBotWebhookReq
	DeleteBotWebhookResp                = pb.DeleteBotWebhookResp
	DeleteUserBotReq                    = pb.DeleteUserBotReq
	DeleteUserBotResp                   = pb.DeleteUserBotResp
	GetBotProfileReq                    = pb.GetBotProfileReq
	GetBotProfileResp                   = pb.GetBotProfileResp
	GetBotWebhookReq                    = pb.GetBotWebhookReq
	GetBotWebhookResp                   = pb.GetBotWebhookResp
	GetUserBotReq                       = pb.GetUserBotReq
	GetUserBotResp                      = pb.GetUserBotResp
	ListBotActionsReq                   = pb.ListBotActionsReq
	ListBotActionsResp                  = pb.ListBotActionsResp
	ListBotConversationsReq             = pb.ListBotConversationsReq
	ListBotConversationsResp            = pb.ListBotConversationsResp
	ListBotEventsReq                    = pb.ListBotEventsReq
	ListBotEventsResp                   = pb.ListBotEventsResp
	ListUserBotTokensReq                = pb.ListUserBotTokensReq
	ListUserBotTokensResp               = pb.ListUserBotTokensResp
	ListUserBotsReq                     = pb.ListUserBotsReq
	ListUserBotsResp                    = pb.ListUserBotsResp
	ResolveBotWebhookEventActionsReq    = pb.ResolveBotWebhookEventActionsReq
	ResolveBotWebhookEventActionsResp   = pb.ResolveBotWebhookEventActionsResp
	RevokeUserBotTokenReq               = pb.RevokeUserBotTokenReq
	RevokeUserBotTokenResp              = pb.RevokeUserBotTokenResp
	RotateUserBotTokenReq               = pb.RotateUserBotTokenReq
	RotateUserBotTokenResp              = pb.RotateUserBotTokenResp
	SetBotWebhookReq                    = pb.SetBotWebhookReq
	SetBotWebhookResp                   = pb.SetBotWebhookResp
	SetUserBotStatusReq                 = pb.SetUserBotStatusReq
	SetUserBotStatusResp                = pb.SetUserBotStatusResp
	UpdateUserBotProfileReq             = pb.UpdateUserBotProfileReq
	UpdateUserBotProfileResp            = pb.UpdateUserBotProfileResp
	UpdateUserBotTokenReq               = pb.UpdateUserBotTokenReq
	UpdateUserBotTokenResp              = pb.UpdateUserBotTokenResp
	ValidateBotTokenReq                 = pb.ValidateBotTokenReq
	ValidateBotTokenResp                = pb.ValidateBotTokenResp

	BotService interface {
		// ValidateBotToken resolves a plaintext token into a bot identity.
		ValidateBotToken(ctx context.Context, in *ValidateBotTokenReq, opts ...grpc.CallOption) (*ValidateBotTokenResp, error)
		// GetBotProfile returns the bot's user_info snapshot for `/api/bot/v1/me`.
		GetBotProfile(ctx context.Context, in *GetBotProfileReq, opts ...grpc.CallOption) (*GetBotProfileResp, error)
		// ListBotConversations returns every conversation the bot is a member of.
		ListBotConversations(ctx context.Context, in *ListBotConversationsReq, opts ...grpc.CallOption) (*ListBotConversationsResp, error)
		// GetBotWebhook returns the bot's webhook configuration without the
		GetBotWebhook(ctx context.Context, in *GetBotWebhookReq, opts ...grpc.CallOption) (*GetBotWebhookResp, error)
		// SetBotWebhook upserts the bot's webhook configuration. The plaintext
		SetBotWebhook(ctx context.Context, in *SetBotWebhookReq, opts ...grpc.CallOption) (*SetBotWebhookResp, error)
		// DeleteBotWebhook removes the bot's webhook configuration entirely.
		DeleteBotWebhook(ctx context.Context, in *DeleteBotWebhookReq, opts ...grpc.CallOption) (*DeleteBotWebhookResp, error)
		// ResolveBotWebhookEventActions maps webhook event names (e.g. message.created)
		ResolveBotWebhookEventActions(ctx context.Context, in *ResolveBotWebhookEventActionsReq, opts ...grpc.CallOption) (*ResolveBotWebhookEventActionsResp, error)
		// User-side Bot management RPCs. Gateway calls these with the authenticated
		CreateUserBot(ctx context.Context, in *CreateUserBotReq, opts ...grpc.CallOption) (*CreateUserBotResp, error)
		ListUserBots(ctx context.Context, in *ListUserBotsReq, opts ...grpc.CallOption) (*ListUserBotsResp, error)
		GetUserBot(ctx context.Context, in *GetUserBotReq, opts ...grpc.CallOption) (*GetUserBotResp, error)
		UpdateUserBotProfile(ctx context.Context, in *UpdateUserBotProfileReq, opts ...grpc.CallOption) (*UpdateUserBotProfileResp, error)
		SetUserBotStatus(ctx context.Context, in *SetUserBotStatusReq, opts ...grpc.CallOption) (*SetUserBotStatusResp, error)
		DeleteUserBot(ctx context.Context, in *DeleteUserBotReq, opts ...grpc.CallOption) (*DeleteUserBotResp, error)
		CreateUserBotToken(ctx context.Context, in *CreateUserBotTokenReq, opts ...grpc.CallOption) (*CreateUserBotTokenResp, error)
		ListUserBotTokens(ctx context.Context, in *ListUserBotTokensReq, opts ...grpc.CallOption) (*ListUserBotTokensResp, error)
		UpdateUserBotToken(ctx context.Context, in *UpdateUserBotTokenReq, opts ...grpc.CallOption) (*UpdateUserBotTokenResp, error)
		RotateUserBotToken(ctx context.Context, in *RotateUserBotTokenReq, opts ...grpc.CallOption) (*RotateUserBotTokenResp, error)
		RevokeUserBotToken(ctx context.Context, in *RevokeUserBotTokenReq, opts ...grpc.CallOption) (*RevokeUserBotTokenResp, error)
		AddUserBotToConversation(ctx context.Context, in *AddUserBotToConversationReq, opts ...grpc.CallOption) (*AddUserBotToConversationResp, error)
		CreateUserBotDirectConversation(ctx context.Context, in *CreateUserBotDirectConversationReq, opts ...grpc.CallOption) (*CreateUserBotDirectConversationResp, error)
		ListBotActions(ctx context.Context, in *ListBotActionsReq, opts ...grpc.CallOption) (*ListBotActionsResp, error)
		ListBotEvents(ctx context.Context, in *ListBotEventsReq, opts ...grpc.CallOption) (*ListBotEventsResp, error)
	}

	defaultBotService struct {
		cli zrpc.Client
	}
)

func NewBotService(cli zrpc.Client) BotService {
	return &defaultBotService{
		cli: cli,
	}
}

// ValidateBotToken resolves a plaintext token into a bot identity.
func (m *defaultBotService) ValidateBotToken(ctx context.Context, in *ValidateBotTokenReq, opts ...grpc.CallOption) (*ValidateBotTokenResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ValidateBotToken(ctx, in, opts...)
}

// GetBotProfile returns the bot's user_info snapshot for `/api/bot/v1/me`.
func (m *defaultBotService) GetBotProfile(ctx context.Context, in *GetBotProfileReq, opts ...grpc.CallOption) (*GetBotProfileResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.GetBotProfile(ctx, in, opts...)
}

// ListBotConversations returns every conversation the bot is a member of.
func (m *defaultBotService) ListBotConversations(ctx context.Context, in *ListBotConversationsReq, opts ...grpc.CallOption) (*ListBotConversationsResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ListBotConversations(ctx, in, opts...)
}

// GetBotWebhook returns the bot's webhook configuration without the
func (m *defaultBotService) GetBotWebhook(ctx context.Context, in *GetBotWebhookReq, opts ...grpc.CallOption) (*GetBotWebhookResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.GetBotWebhook(ctx, in, opts...)
}

// SetBotWebhook upserts the bot's webhook configuration. The plaintext
func (m *defaultBotService) SetBotWebhook(ctx context.Context, in *SetBotWebhookReq, opts ...grpc.CallOption) (*SetBotWebhookResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.SetBotWebhook(ctx, in, opts...)
}

// DeleteBotWebhook removes the bot's webhook configuration entirely.
func (m *defaultBotService) DeleteBotWebhook(ctx context.Context, in *DeleteBotWebhookReq, opts ...grpc.CallOption) (*DeleteBotWebhookResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.DeleteBotWebhook(ctx, in, opts...)
}

// ResolveBotWebhookEventActions maps webhook event names (e.g. message.created)
func (m *defaultBotService) ResolveBotWebhookEventActions(ctx context.Context, in *ResolveBotWebhookEventActionsReq, opts ...grpc.CallOption) (*ResolveBotWebhookEventActionsResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ResolveBotWebhookEventActions(ctx, in, opts...)
}

// User-side Bot management RPCs. Gateway calls these with the authenticated
func (m *defaultBotService) CreateUserBot(ctx context.Context, in *CreateUserBotReq, opts ...grpc.CallOption) (*CreateUserBotResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.CreateUserBot(ctx, in, opts...)
}

func (m *defaultBotService) ListUserBots(ctx context.Context, in *ListUserBotsReq, opts ...grpc.CallOption) (*ListUserBotsResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ListUserBots(ctx, in, opts...)
}

func (m *defaultBotService) GetUserBot(ctx context.Context, in *GetUserBotReq, opts ...grpc.CallOption) (*GetUserBotResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.GetUserBot(ctx, in, opts...)
}

func (m *defaultBotService) UpdateUserBotProfile(ctx context.Context, in *UpdateUserBotProfileReq, opts ...grpc.CallOption) (*UpdateUserBotProfileResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.UpdateUserBotProfile(ctx, in, opts...)
}

func (m *defaultBotService) SetUserBotStatus(ctx context.Context, in *SetUserBotStatusReq, opts ...grpc.CallOption) (*SetUserBotStatusResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.SetUserBotStatus(ctx, in, opts...)
}

func (m *defaultBotService) DeleteUserBot(ctx context.Context, in *DeleteUserBotReq, opts ...grpc.CallOption) (*DeleteUserBotResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.DeleteUserBot(ctx, in, opts...)
}

func (m *defaultBotService) CreateUserBotToken(ctx context.Context, in *CreateUserBotTokenReq, opts ...grpc.CallOption) (*CreateUserBotTokenResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.CreateUserBotToken(ctx, in, opts...)
}

func (m *defaultBotService) ListUserBotTokens(ctx context.Context, in *ListUserBotTokensReq, opts ...grpc.CallOption) (*ListUserBotTokensResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ListUserBotTokens(ctx, in, opts...)
}

func (m *defaultBotService) UpdateUserBotToken(ctx context.Context, in *UpdateUserBotTokenReq, opts ...grpc.CallOption) (*UpdateUserBotTokenResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.UpdateUserBotToken(ctx, in, opts...)
}

func (m *defaultBotService) RotateUserBotToken(ctx context.Context, in *RotateUserBotTokenReq, opts ...grpc.CallOption) (*RotateUserBotTokenResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.RotateUserBotToken(ctx, in, opts...)
}

func (m *defaultBotService) RevokeUserBotToken(ctx context.Context, in *RevokeUserBotTokenReq, opts ...grpc.CallOption) (*RevokeUserBotTokenResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.RevokeUserBotToken(ctx, in, opts...)
}

func (m *defaultBotService) AddUserBotToConversation(ctx context.Context, in *AddUserBotToConversationReq, opts ...grpc.CallOption) (*AddUserBotToConversationResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.AddUserBotToConversation(ctx, in, opts...)
}

func (m *defaultBotService) CreateUserBotDirectConversation(ctx context.Context, in *CreateUserBotDirectConversationReq, opts ...grpc.CallOption) (*CreateUserBotDirectConversationResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.CreateUserBotDirectConversation(ctx, in, opts...)
}

func (m *defaultBotService) ListBotActions(ctx context.Context, in *ListBotActionsReq, opts ...grpc.CallOption) (*ListBotActionsResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ListBotActions(ctx, in, opts...)
}

func (m *defaultBotService) ListBotEvents(ctx context.Context, in *ListBotEventsReq, opts ...grpc.CallOption) (*ListBotEventsResp, error) {
	client := pb.NewBotServiceClient(m.cli.Conn())
	return client.ListBotEvents(ctx, in, opts...)
}
