// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package conversationservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateConversationReq       = pb.CreateConversationReq
	CreateConversationResp      = pb.CreateConversationResp
	GetConversationHistoryReq   = pb.GetConversationHistoryReq
	GetConversationHistoryResp  = pb.GetConversationHistoryResp
	GetConversationMembersReq   = pb.GetConversationMembersReq
	GetConversationMembersResp  = pb.GetConversationMembersResp
	GetUserConversationsReq     = pb.GetUserConversationsReq
	GetUserConversationsResp    = pb.GetUserConversationsResp

	ConversationService interface {
		// CreateConversation creates a new conversation (direct or group).
		CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*CreateConversationResp, error)
		// GetConversationHistory retrieves message history for a conversation with cursor-based pagination.
		GetConversationHistory(ctx context.Context, in *GetConversationHistoryReq, opts ...grpc.CallOption) (*GetConversationHistoryResp, error)
		// GetConversationMembers retrieves the member IDs for a conversation.
		GetConversationMembers(ctx context.Context, in *GetConversationMembersReq, opts ...grpc.CallOption) (*GetConversationMembersResp, error)
		// GetUserConversations retrieves all conversations the user is a member of.
		GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error)
	}

	defaultConversationService struct {
		cli zrpc.Client
	}
)

func NewConversationService(cli zrpc.Client) ConversationService {
	return &defaultConversationService{
		cli: cli,
	}
}

// CreateConversation creates a new conversation (direct or group).
func (m *defaultConversationService) CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*CreateConversationResp, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

// GetConversationHistory retrieves message history for a conversation with cursor-based pagination.
func (m *defaultConversationService) GetConversationHistory(ctx context.Context, in *GetConversationHistoryReq, opts ...grpc.CallOption) (*GetConversationHistoryResp, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.GetConversationHistory(ctx, in, opts...)
}

// GetConversationMembers retrieves the member IDs for a conversation.
func (m *defaultConversationService) GetConversationMembers(ctx context.Context, in *GetConversationMembersReq, opts ...grpc.CallOption) (*GetConversationMembersResp, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.GetConversationMembers(ctx, in, opts...)
}

// GetUserConversations retrieves all conversations the user is a member of.
func (m *defaultConversationService) GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.GetUserConversations(ctx, in, opts...)
}
