// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package permissionservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckMessagePermissionReq  = pb.CheckMessagePermissionReq
	CheckMessagePermissionResp = pb.CheckMessagePermissionResp

	PermissionService interface {
		// CheckMessagePermission checks whether a sender can publish into a conversation.
		CheckMessagePermission(ctx context.Context, in *CheckMessagePermissionReq, opts ...grpc.CallOption) (*CheckMessagePermissionResp, error)
	}

	defaultPermissionService struct {
		cli zrpc.Client
	}
)

func NewPermissionService(cli zrpc.Client) PermissionService {
	return &defaultPermissionService{
		cli: cli,
	}
}

// CheckMessagePermission checks whether a sender can publish into a conversation.
func (m *defaultPermissionService) CheckMessagePermission(ctx context.Context, in *CheckMessagePermissionReq, opts ...grpc.CallOption) (*CheckMessagePermissionResp, error) {
	client := pb.NewPermissionServiceClient(m.cli.Conn())
	return client.CheckMessagePermission(ctx, in, opts...)
}
