// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package server

import (
	"context"

	"github.com/hellopoisonx/aim/app/auth/rpc/internal/logic"
	"github.com/hellopoisonx/aim/app/auth/rpc/internal/svc"
	"github.com/hellopoisonx/aim/app/auth/rpc/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServiceServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AuthServiceServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// CreateBotCredential creates a disabled placeholder credential for a bot.
func (s *AuthServiceServer) CreateBotCredential(ctx context.Context, in *pb.CreateBotCredentialReq) (*pb.CreateBotCredentialResp, error) {
	l := logic.NewCreateBotCredentialLogic(ctx, s.svcCtx)
	return l.CreateBotCredential(in)
}
