// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package userservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserInfoReq            = pb.CreateUserInfoReq
	CreateUserInfoResp           = pb.CreateUserInfoResp
	GetUserInfoByEmailReq        = pb.GetUserInfoByEmailReq
	GetUserInfoByNicknameReq     = pb.GetUserInfoByNicknameReq
	GetUserInfoReq               = pb.GetUserInfoReq
	GetUserInfoResp              = pb.GetUserInfoResp
	SearchUserInfoByNicknameReq  = pb.SearchUserInfoByNicknameReq
	SearchUserInfoByNicknameResp = pb.SearchUserInfoByNicknameResp
	UpdateUserInfoProfileReq     = pb.UpdateUserInfoProfileReq
	UpdateUserInfoProfileResp    = pb.UpdateUserInfoProfileResp
	UpdateUserInfoStatusReq      = pb.UpdateUserInfoStatusReq
	UpdateUserInfoStatusResp     = pb.UpdateUserInfoStatusResp

	UserService interface {
		// CreateUserInfo creates a new user profile.
		CreateUserInfo(ctx context.Context, in *CreateUserInfoReq, opts ...grpc.CallOption) (*CreateUserInfoResp, error)
		// GetUserInfo retrieves a user profile by ID.
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// GetUserInfoByEmail retrieves a user profile by email.
		GetUserInfoByEmail(ctx context.Context, in *GetUserInfoByEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// GetUserInfoByNickname retrieves a user profile by exact nickname.
		GetUserInfoByNickname(ctx context.Context, in *GetUserInfoByNicknameReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// UpdateUserInfoProfile updates nickname and avatar.
		UpdateUserInfoProfile(ctx context.Context, in *UpdateUserInfoProfileReq, opts ...grpc.CallOption) (*UpdateUserInfoProfileResp, error)
		// UpdateUserInfoStatus updates user status.
		UpdateUserInfoStatus(ctx context.Context, in *UpdateUserInfoStatusReq, opts ...grpc.CallOption) (*UpdateUserInfoStatusResp, error)
		// SearchUserInfoByNickname searches user profiles by nickname prefix.
		SearchUserInfoByNickname(ctx context.Context, in *SearchUserInfoByNicknameReq, opts ...grpc.CallOption) (*SearchUserInfoByNicknameResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// CreateUserInfo creates a new user profile.
func (m *defaultUserService) CreateUserInfo(ctx context.Context, in *CreateUserInfoReq, opts ...grpc.CallOption) (*CreateUserInfoResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.CreateUserInfo(ctx, in, opts...)
}

// GetUserInfo retrieves a user profile by ID.
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// GetUserInfoByEmail retrieves a user profile by email.
func (m *defaultUserService) GetUserInfoByEmail(ctx context.Context, in *GetUserInfoByEmailReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoByEmail(ctx, in, opts...)
}

// GetUserInfoByNickname retrieves a user profile by exact nickname.
func (m *defaultUserService) GetUserInfoByNickname(ctx context.Context, in *GetUserInfoByNicknameReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoByNickname(ctx, in, opts...)
}

// UpdateUserInfoProfile updates nickname and avatar.
func (m *defaultUserService) UpdateUserInfoProfile(ctx context.Context, in *UpdateUserInfoProfileReq, opts ...grpc.CallOption) (*UpdateUserInfoProfileResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfoProfile(ctx, in, opts...)
}

// UpdateUserInfoStatus updates user status.
func (m *defaultUserService) UpdateUserInfoStatus(ctx context.Context, in *UpdateUserInfoStatusReq, opts ...grpc.CallOption) (*UpdateUserInfoStatusResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfoStatus(ctx, in, opts...)
}

// SearchUserInfoByNickname searches user profiles by nickname prefix.
func (m *defaultUserService) SearchUserInfoByNickname(ctx context.Context, in *SearchUserInfoByNicknameReq, opts ...grpc.CallOption) (*SearchUserInfoByNicknameResp, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SearchUserInfoByNickname(ctx, in, opts...)
}
