// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: core.proto

package transferservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/core/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TransferReq  = pb.TransferReq
	TransferResp = pb.TransferResp

	TransferService interface {
		// Transfer 将消息路由到核心服务进行投递
		Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	}

	defaultTransferService struct {
		cli zrpc.Client
	}
)

func NewTransferService(cli zrpc.Client) TransferService {
	return &defaultTransferService{
		cli: cli,
	}
}

// Transfer 将消息路由到核心服务进行投递
func (m *defaultTransferService) Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	client := pb.NewTransferServiceClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}
