// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriend(arg1) {
  return window['go']['main']['App']['AcceptFriend'](arg1);
}

export function AddFriend(arg1) {
  return window['go']['main']['App']['AddFriend'](arg1);
}

export function Configure(arg1) {
  return window['go']['main']['App']['Configure'](arg1);
}

export function ConnectWS() {
  return window['go']['main']['App']['ConnectWS']();
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CreateDirectConversation(arg1) {
  return window['go']['main']['App']['CreateDirectConversation'](arg1);
}

export function DeviceID() {
  return window['go']['main']['App']['DeviceID']();
}

export function DisconnectWS() {
  return window['go']['main']['App']['DisconnectWS']();
}

export function GetConversationHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetConversationHistory'](arg1, arg2, arg3, arg4);
}

export function GetUserById(arg1) {
  return window['go']['main']['App']['GetUserById'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListFriendApplications() {
  return window['go']['main']['App']['ListFriendApplications']();
}

export function ListFriends() {
  return window['go']['main']['App']['ListFriends']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ProtocolCatalog() {
  return window['go']['main']['App']['ProtocolCatalog']();
}

export function Refresh(arg1) {
  return window['go']['main']['App']['Refresh'](arg1);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RejectFriend(arg1) {
  return window['go']['main']['App']['RejectFriend'](arg1);
}

export function SearchUsersByName(arg1) {
  return window['go']['main']['App']['SearchUsersByName'](arg1);
}

export function SendAck(arg1) {
  return window['go']['main']['App']['SendAck'](arg1);
}

export function SendHeartbeat(arg1) {
  return window['go']['main']['App']['SendHeartbeat'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendReadReceipt(arg1, arg2) {
  return window['go']['main']['App']['SendReadReceipt'](arg1, arg2);
}

export function SendTyping(arg1) {
  return window['go']['main']['App']['SendTyping'](arg1);
}

export function SessionState() {
  return window['go']['main']['App']['SessionState']();
}
