// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';

export function Configure(arg1:main.AppConfig):Promise<main.SessionState>;

export function ConnectWS():Promise<void>;

export function DeviceID():Promise<string>;

export function DisconnectWS():Promise<void>;

export function Login(arg1:client.LoginRequest):Promise<client.LoginResponse>;

export function Logout():Promise<client.LogoutResponse>;

export function ProtocolCatalog():Promise<main.ProtocolCatalog>;

export function Refresh(arg1:client.RefreshRequest):Promise<client.RefreshResponse>;

export function Register(arg1:client.RegisterRequest):Promise<client.RegisterResponse>;

export function SendAck(arg1:number):Promise<void>;

export function SendHeartbeat(arg1:number):Promise<void>;

export function SendMessage(arg1:main.SendMessageRequest):Promise<void>;

export function SendReadReceipt(arg1:number,arg2:number):Promise<void>;

export function SendTyping(arg1:number):Promise<void>;

export function SessionState():Promise<main.SessionState>;
