// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: shared/proto/gateway/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderInfo) Reset() {
	*x = SenderInfo{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderInfo) ProtoMessage() {}

func (x *SenderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderInfo.ProtoReflect.Descriptor instead.
func (*SenderInfo) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SenderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SenderInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// PushMessageReq — 投递聊天消息请求
type PushMessageReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                     // 消息全局唯一 ID
	ConversationId   int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`      // 会话 ID
	ConversationType string                 `protobuf:"bytes,3,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // 会话类型：direct/group（与 logic.conversations.conversation_type 一致）
	MessageType      string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                // 消息类型：text/image/voice/etc
	Content          string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                           // 消息内容
	SenderId         int64                  `protobuf:"varint,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                        // 发送者用户 ID
	SentAt           int64                  `protobuf:"varint,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`                              // 发送时间戳（毫秒）
	ClientMsgId      string                 `protobuf:"bytes,8,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`              // 客户端消息 ID（用于去重）
	Mentions         []string               `protobuf:"bytes,9,rep,name=mentions,proto3" json:"mentions,omitempty"`                                         // 被 @ 的用户 ID 列表
	TargetUserId     int64                  `protobuf:"varint,10,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`         // 目标用户 ID（投递到此用户在本节点的所有连接）
	IsSystem         bool                   `protobuf:"varint,11,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`                       // true 表示群变更系统消息
	SenderInfo       *SenderInfo            `protobuf:"bytes,12,opt,name=sender_info,json=senderInfo,proto3" json:"sender_info,omitempty"`                  // 发送者信息快照
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushMessageReq) Reset() {
	*x = PushMessageReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageReq) ProtoMessage() {}

func (x *PushMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageReq.ProtoReflect.Descriptor instead.
func (*PushMessageReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PushMessageReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *PushMessageReq) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *PushMessageReq) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PushMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PushMessageReq) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *PushMessageReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *PushMessageReq) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *PushMessageReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *PushMessageReq) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *PushMessageReq) GetSenderInfo() *SenderInfo {
	if x != nil {
		return x.SenderInfo
	}
	return nil
}

// PushMessageResp — 投递聊天消息响应
type PushMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功投递到网关节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageResp) Reset() {
	*x = PushMessageResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResp) ProtoMessage() {}

func (x *PushMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResp.ProtoReflect.Descriptor instead.
func (*PushMessageResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PushMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PushPresenceReq — 推送用户在线状态请求
type PushPresenceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 状态变更的用户 ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // 状态：online/offline
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // 状态变更时间戳（毫秒）
	TargetUserId  int64                  `protobuf:"varint,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 目标用户 ID（投递到此用户在本节点的所有连接）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPresenceReq) Reset() {
	*x = PushPresenceReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPresenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPresenceReq) ProtoMessage() {}

func (x *PushPresenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPresenceReq.ProtoReflect.Descriptor instead.
func (*PushPresenceReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PushPresenceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushPresenceReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PushPresenceReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PushPresenceReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// PushPresenceResp — 推送用户在线状态响应
type PushPresenceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功推送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPresenceResp) Reset() {
	*x = PushPresenceResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPresenceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPresenceResp) ProtoMessage() {}

func (x *PushPresenceResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPresenceResp.ProtoReflect.Descriptor instead.
func (*PushPresenceResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PushPresenceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PushTypingReq — 推送输入状态请求
type PushTypingReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId   int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`     // 目标用户 ID（投递到此用户在本节点的所有连接）
	FromUserId     int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`           // 正在输入的用户 ID
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话 ID
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // 事件时间戳（毫秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushTypingReq) Reset() {
	*x = PushTypingReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTypingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTypingReq) ProtoMessage() {}

func (x *PushTypingReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTypingReq.ProtoReflect.Descriptor instead.
func (*PushTypingReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *PushTypingReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *PushTypingReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *PushTypingReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *PushTypingReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PushTypingResp — 推送输入状态响应
type PushTypingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功推送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTypingResp) Reset() {
	*x = PushTypingResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTypingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTypingResp) ProtoMessage() {}

func (x *PushTypingResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTypingResp.ProtoReflect.Descriptor instead.
func (*PushTypingResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PushTypingResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PushFriendApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFriendApplicationReq) Reset() {
	*x = PushFriendApplicationReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFriendApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFriendApplicationReq) ProtoMessage() {}

func (x *PushFriendApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFriendApplicationReq.ProtoReflect.Descriptor instead.
func (*PushFriendApplicationReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *PushFriendApplicationReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *PushFriendApplicationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushFriendApplicationReq) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *PushFriendApplicationReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PushFriendApplicationReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PushFriendApplicationReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PushFriendApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFriendApplicationResp) Reset() {
	*x = PushFriendApplicationResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFriendApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFriendApplicationResp) ProtoMessage() {}

func (x *PushFriendApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFriendApplicationResp.ProtoReflect.Descriptor instead.
func (*PushFriendApplicationResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *PushFriendApplicationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PushReadReceiptReq — 推送已读回执请求
type PushReadReceiptReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId      int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`                  // 目标用户 ID（投递到此用户在本节点的所有连接）
	ConversationId    int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`              // 会话 ID
	FromUserId        int64                  `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`                        // 推进游标的成员
	LastReadMessageId int64                  `protobuf:"varint,4,opt,name=last_read_message_id,json=lastReadMessageId,proto3" json:"last_read_message_id,omitempty"` // 该成员已读到的最大消息 ID
	UpdatedAt         int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                             // 已读游标的更新时间（毫秒）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushReadReceiptReq) Reset() {
	*x = PushReadReceiptReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReadReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReadReceiptReq) ProtoMessage() {}

func (x *PushReadReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReadReceiptReq.ProtoReflect.Descriptor instead.
func (*PushReadReceiptReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *PushReadReceiptReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *PushReadReceiptReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *PushReadReceiptReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *PushReadReceiptReq) GetLastReadMessageId() int64 {
	if x != nil {
		return x.LastReadMessageId
	}
	return 0
}

func (x *PushReadReceiptReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// PushReadReceiptResp — 推送已读回执响应
type PushReadReceiptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReadReceiptResp) Reset() {
	*x = PushReadReceiptResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReadReceiptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReadReceiptResp) ProtoMessage() {}

func (x *PushReadReceiptResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReadReceiptResp.ProtoReflect.Descriptor instead.
func (*PushReadReceiptResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *PushReadReceiptResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PushNotificationReq — 推送系统通知请求
type PushNotificationReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId     int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`          // 目标用户 ID，0 表示广播本节点所有连接
	NotificationType string                 `protobuf:"bytes,2,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"` // 通知类型：announcement / maintenance / force_update / ...
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                               // 标题
	Body             string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                 // 正文
	RelatedId        int64                  `protobuf:"varint,5,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`                     // 关联 ID（业务自定义，可为 0）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushNotificationReq) Reset() {
	*x = PushNotificationReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationReq) ProtoMessage() {}

func (x *PushNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationReq.ProtoReflect.Descriptor instead.
func (*PushNotificationReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *PushNotificationReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *PushNotificationReq) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *PushNotificationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushNotificationReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushNotificationReq) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

// PushNotificationResp — 推送系统通知响应
type PushNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 是否成功推送（任一连接失败时返回 false）
	AffectedCount int32                  `protobuf:"varint,2,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"` // 实际推送到的连接数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotificationResp) Reset() {
	*x = PushNotificationResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationResp) ProtoMessage() {}

func (x *PushNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationResp.ProtoReflect.Descriptor instead.
func (*PushNotificationResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *PushNotificationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushNotificationResp) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

// KickUserReq — 踢出用户请求
type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户 ID
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备 ID（空字符串表示踢掉所有设备）
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                     // 踢人原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *KickUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickUserReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KickUserReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// KickUserResp — 踢出用户响应
type KickUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KickedCount   int32                  `protobuf:"varint,1,opt,name=kicked_count,json=kickedCount,proto3" json:"kicked_count,omitempty"` // 被踢出的连接数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResp) Reset() {
	*x = KickUserResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResp) ProtoMessage() {}

func (x *KickUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResp.ProtoReflect.Descriptor instead.
func (*KickUserResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *KickUserResp) GetKickedCount() int32 {
	if x != nil {
		return x.KickedCount
	}
	return 0
}

// DrainNotifyReq — 通知网关节点即将关闭请求
type DrainNotifyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DrainTimeoutMs int64                  `protobuf:"varint,1,opt,name=drain_timeout_ms,json=drainTimeoutMs,proto3" json:"drain_timeout_ms,omitempty"` // drain 超时时间（毫秒），客户端需在此时间内重连
	GatewayNodeId  string                 `protobuf:"bytes,2,opt,name=gateway_node_id,json=gatewayNodeId,proto3" json:"gateway_node_id,omitempty"`     // 网关节点 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainNotifyReq) Reset() {
	*x = DrainNotifyReq{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNotifyReq) ProtoMessage() {}

func (x *DrainNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNotifyReq.ProtoReflect.Descriptor instead.
func (*DrainNotifyReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *DrainNotifyReq) GetDrainTimeoutMs() int64 {
	if x != nil {
		return x.DrainTimeoutMs
	}
	return 0
}

func (x *DrainNotifyReq) GetGatewayNodeId() string {
	if x != nil {
		return x.GatewayNodeId
	}
	return ""
}

// DrainNotifyResp — 通知网关节点即将关闭响应
type DrainNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedCount int32                  `protobuf:"varint,1,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"` // 受影响的连接数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNotifyResp) Reset() {
	*x = DrainNotifyResp{}
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNotifyResp) ProtoMessage() {}

func (x *DrainNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNotifyResp.ProtoReflect.Descriptor instead.
func (*DrainNotifyResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *DrainNotifyResp) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

var File_shared_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_shared_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\"shared/proto/gateway/gateway.proto\x12\agateway\"6\n" +
	"\n" +
	"SenderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xb1\x03\n" +
	"\x0ePushMessageReq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12+\n" +
	"\x11conversation_type\x18\x03 \x01(\tR\x10conversationType\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\x03R\bsenderId\x12\x17\n" +
	"\asent_at\x18\a \x01(\x03R\x06sentAt\x12\"\n" +
	"\rclient_msg_id\x18\b \x01(\tR\vclientMsgId\x12\x1a\n" +
	"\bmentions\x18\t \x03(\tR\bmentions\x12$\n" +
	"\x0etarget_user_id\x18\n" +
	" \x01(\x03R\ftargetUserId\x12\x1b\n" +
	"\tis_system\x18\v \x01(\bR\bisSystem\x124\n" +
	"\vsender_info\x18\f \x01(\v2\x13.gateway.SenderInfoR\n" +
	"senderInfo\"+\n" +
	"\x0fPushMessageResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\x0fPushPresenceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\x03R\ftargetUserId\",\n" +
	"\x10PushPresenceResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\rPushTypingReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"*\n" +
	"\x0ePushTypingResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x18PushFriendApplicationReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x03 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"5\n" +
	"\x19PushFriendApplicationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd5\x01\n" +
	"\x12PushReadReceiptReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x03R\n" +
	"fromUserId\x12/\n" +
	"\x14last_read_message_id\x18\x04 \x01(\x03R\x11lastReadMessageId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"/\n" +
	"\x13PushReadReceiptResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb1\x01\n" +
	"\x13PushNotificationReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12+\n" +
	"\x11notification_type\x18\x02 \x01(\tR\x10notificationType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"related_id\x18\x05 \x01(\x03R\trelatedId\"W\n" +
	"\x14PushNotificationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eaffected_count\x18\x02 \x01(\x05R\raffectedCount\"[\n" +
	"\vKickUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"1\n" +
	"\fKickUserResp\x12!\n" +
	"\fkicked_count\x18\x01 \x01(\x05R\vkickedCount\"b\n" +
	"\x0eDrainNotifyReq\x12(\n" +
	"\x10drain_timeout_ms\x18\x01 \x01(\x03R\x0edrainTimeoutMs\x12&\n" +
	"\x0fgateway_node_id\x18\x02 \x01(\tR\rgatewayNodeId\"8\n" +
	"\x0fDrainNotifyResp\x12%\n" +
	"\x0eaffected_count\x18\x01 \x01(\x05R\raffectedCount2\xd0\x04\n" +
	"\x0eGatewayService\x12@\n" +
	"\vPushMessage\x12\x17.gateway.PushMessageReq\x1a\x18.gateway.PushMessageResp\x12C\n" +
	"\fPushPresence\x12\x18.gateway.PushPresenceReq\x1a\x19.gateway.PushPresenceResp\x12=\n" +
	"\n" +
	"PushTyping\x12\x16.gateway.PushTypingReq\x1a\x17.gateway.PushTypingResp\x12^\n" +
	"\x15PushFriendApplication\x12!.gateway.PushFriendApplicationReq\x1a\".gateway.PushFriendApplicationResp\x12L\n" +
	"\x0fPushReadReceipt\x12\x1b.gateway.PushReadReceiptReq\x1a\x1c.gateway.PushReadReceiptResp\x12O\n" +
	"\x10PushNotification\x12\x1c.gateway.PushNotificationReq\x1a\x1d.gateway.PushNotificationResp\x127\n" +
	"\bKickUser\x12\x14.gateway.KickUserReq\x1a\x15.gateway.KickUserResp\x12@\n" +
	"\vDrainNotify\x12\x17.gateway.DrainNotifyReq\x1a\x18.gateway.DrainNotifyRespB5Z3github.com/hellopoisonx/aim/shared/proto/gateway/pbb\x06proto3"

var (
	file_shared_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_shared_proto_gateway_gateway_proto_rawDescData []byte
)

func file_shared_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_shared_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_shared_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_gateway_gateway_proto_rawDesc), len(file_shared_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_shared_proto_gateway_gateway_proto_rawDescData
}

var file_shared_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_shared_proto_gateway_gateway_proto_goTypes = []any{
	(*SenderInfo)(nil),                // 0: gateway.SenderInfo
	(*PushMessageReq)(nil),            // 1: gateway.PushMessageReq
	(*PushMessageResp)(nil),           // 2: gateway.PushMessageResp
	(*PushPresenceReq)(nil),           // 3: gateway.PushPresenceReq
	(*PushPresenceResp)(nil),          // 4: gateway.PushPresenceResp
	(*PushTypingReq)(nil),             // 5: gateway.PushTypingReq
	(*PushTypingResp)(nil),            // 6: gateway.PushTypingResp
	(*PushFriendApplicationReq)(nil),  // 7: gateway.PushFriendApplicationReq
	(*PushFriendApplicationResp)(nil), // 8: gateway.PushFriendApplicationResp
	(*PushReadReceiptReq)(nil),        // 9: gateway.PushReadReceiptReq
	(*PushReadReceiptResp)(nil),       // 10: gateway.PushReadReceiptResp
	(*PushNotificationReq)(nil),       // 11: gateway.PushNotificationReq
	(*PushNotificationResp)(nil),      // 12: gateway.PushNotificationResp
	(*KickUserReq)(nil),               // 13: gateway.KickUserReq
	(*KickUserResp)(nil),              // 14: gateway.KickUserResp
	(*DrainNotifyReq)(nil),            // 15: gateway.DrainNotifyReq
	(*DrainNotifyResp)(nil),           // 16: gateway.DrainNotifyResp
}
var file_shared_proto_gateway_gateway_proto_depIdxs = []int32{
	0,  // 0: gateway.PushMessageReq.sender_info:type_name -> gateway.SenderInfo
	1,  // 1: gateway.GatewayService.PushMessage:input_type -> gateway.PushMessageReq
	3,  // 2: gateway.GatewayService.PushPresence:input_type -> gateway.PushPresenceReq
	5,  // 3: gateway.GatewayService.PushTyping:input_type -> gateway.PushTypingReq
	7,  // 4: gateway.GatewayService.PushFriendApplication:input_type -> gateway.PushFriendApplicationReq
	9,  // 5: gateway.GatewayService.PushReadReceipt:input_type -> gateway.PushReadReceiptReq
	11, // 6: gateway.GatewayService.PushNotification:input_type -> gateway.PushNotificationReq
	13, // 7: gateway.GatewayService.KickUser:input_type -> gateway.KickUserReq
	15, // 8: gateway.GatewayService.DrainNotify:input_type -> gateway.DrainNotifyReq
	2,  // 9: gateway.GatewayService.PushMessage:output_type -> gateway.PushMessageResp
	4,  // 10: gateway.GatewayService.PushPresence:output_type -> gateway.PushPresenceResp
	6,  // 11: gateway.GatewayService.PushTyping:output_type -> gateway.PushTypingResp
	8,  // 12: gateway.GatewayService.PushFriendApplication:output_type -> gateway.PushFriendApplicationResp
	10, // 13: gateway.GatewayService.PushReadReceipt:output_type -> gateway.PushReadReceiptResp
	12, // 14: gateway.GatewayService.PushNotification:output_type -> gateway.PushNotificationResp
	14, // 15: gateway.GatewayService.KickUser:output_type -> gateway.KickUserResp
	16, // 16: gateway.GatewayService.DrainNotify:output_type -> gateway.DrainNotifyResp
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_gateway_gateway_proto_init() }
func file_shared_proto_gateway_gateway_proto_init() {
	if File_shared_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_gateway_gateway_proto_rawDesc), len(file_shared_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_shared_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_shared_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_shared_proto_gateway_gateway_proto = out.File
	file_shared_proto_gateway_gateway_proto_goTypes = nil
	file_shared_proto_gateway_gateway_proto_depIdxs = nil
}
