// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/auth"
	conversations "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/conversations"
	friends "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/friends"
	users "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/users"
	"github.com/hellopoisonx/aim/app/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: conversations.CreateConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/history/:id",
					Handler: conversations.GetConversationHistoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/conversations"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/accept/:id",
					Handler: friends.AcceptFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/applications",
					Handler: friends.ListFriendApplicationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: friends.ListFriendsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reject/:id",
					Handler: friends.RejectFriendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/friends"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/by-id/:id",
					Handler: users.GetUserByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/by-name/:name",
					Handler: users.GetUserByNameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friends/:id",
					Handler: users.AddFriendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/users"),
	)
}
