// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/auth"
	users "github.com/hellopoisonx/aim/app/gateway/api/internal/handler/users"
	"github.com/hellopoisonx/aim/app/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/by-id/:id",
				Handler: users.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/by-name/:name",
				Handler: users.GetUserByNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/users"),
	)
}
