// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (UpdateStatusRow, error)
}

var _ Querier = (*Queries)(nil)
