// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriend(arg1) {
  return window['go']['main']['App']['AcceptFriend'](arg1);
}

export function AddFriend(arg1) {
  return window['go']['main']['App']['AddFriend'](arg1);
}

export function AddGroupMembers(arg1, arg2) {
  return window['go']['main']['App']['AddGroupMembers'](arg1, arg2);
}

export function AutoLogin() {
  return window['go']['main']['App']['AutoLogin']();
}

export function ChooseAttachmentAndSend(arg1) {
  return window['go']['main']['App']['ChooseAttachmentAndSend'](arg1);
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DismissGroup(arg1) {
  return window['go']['main']['App']['DismissGroup'](arg1);
}

export function GetAttachment(arg1) {
  return window['go']['main']['App']['GetAttachment'](arg1);
}

export function GetAttachmentDownload(arg1) {
  return window['go']['main']['App']['GetAttachmentDownload'](arg1);
}

export function GetCachedConversationMembers(arg1) {
  return window['go']['main']['App']['GetCachedConversationMembers'](arg1);
}

export function GetCachedConversations() {
  return window['go']['main']['App']['GetCachedConversations']();
}

export function GetCachedFriends() {
  return window['go']['main']['App']['GetCachedFriends']();
}

export function GetCachedMessages(arg1, arg2) {
  return window['go']['main']['App']['GetCachedMessages'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversationHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetConversationHistory'](arg1, arg2, arg3, arg4);
}

export function GetConversationMembers(arg1) {
  return window['go']['main']['App']['GetConversationMembers'](arg1);
}

export function GetFriendsPresence() {
  return window['go']['main']['App']['GetFriendsPresence']();
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GrantGroupAdmin(arg1, arg2) {
  return window['go']['main']['App']['GrantGroupAdmin'](arg1, arg2);
}

export function LeaveGroup(arg1) {
  return window['go']['main']['App']['LeaveGroup'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListFriendApplications() {
  return window['go']['main']['App']['ListFriendApplications']();
}

export function ListFriends() {
  return window['go']['main']['App']['ListFriends']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RefreshToken() {
  return window['go']['main']['App']['RefreshToken']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RejectFriend(arg1) {
  return window['go']['main']['App']['RejectFriend'](arg1);
}

export function RemoveGroupMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveGroupMember'](arg1, arg2);
}

export function RevokeGroupAdmin(arg1, arg2) {
  return window['go']['main']['App']['RevokeGroupAdmin'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendReadReceipt(arg1, arg2) {
  return window['go']['main']['App']['SendReadReceipt'](arg1, arg2);
}

export function SendTyping(arg1) {
  return window['go']['main']['App']['SendTyping'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function TransferGroupOwner(arg1, arg2) {
  return window['go']['main']['App']['TransferGroupOwner'](arg1, arg2);
}

export function UpdateGroupInfo(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupInfo'](arg1, arg2);
}

export function UploadAttachmentAndSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadAttachmentAndSend'](arg1, arg2, arg3);
}
