// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFriend(arg1:string):Promise<main.FriendView>;

export function AddFriend(arg1:string):Promise<main.FriendView>;

export function AddGroupMembers(arg1:string,arg2:Array<string>):Promise<main.ConversationView>;

export function AutoLogin():Promise<main.SessionInfo>;

export function ChooseAttachmentAndSend(arg1:string):Promise<main.MessageView>;

export function CreateConversation(arg1:main.CreateConversationRequest):Promise<main.ConversationView>;

export function CreateGroup(arg1:main.CreateGroupRequest):Promise<main.ConversationView>;

export function DismissGroup(arg1:string):Promise<void>;

export function GetAttachment(arg1:string):Promise<main.AttachmentView>;

export function GetAttachmentDownload(arg1:string):Promise<main.AttachmentDownloadView>;

export function GetCachedConversationMembers(arg1:string):Promise<Array<main.MemberView>>;

export function GetCachedConversations():Promise<Array<main.ConversationView>>;

export function GetCachedFriends():Promise<Array<main.FriendView>>;

export function GetCachedMessages(arg1:string,arg2:number):Promise<Array<main.MessageView>>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetConversationHistory(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.HistoryResponse>;

export function GetConversationMembers(arg1:string):Promise<Array<main.MemberView>>;

export function GetFriendsPresence():Promise<Array<main.PresenceView>>;

export function GetUserByID(arg1:string):Promise<main.UserView>;

export function GrantGroupAdmin(arg1:string,arg2:string):Promise<void>;

export function LeaveGroup(arg1:string):Promise<void>;

export function ListAccounts():Promise<Array<main.AccountView>>;

export function ListConversations():Promise<Array<main.ConversationView>>;

export function ListFriendApplications():Promise<Array<main.FriendView>>;

export function ListFriends():Promise<Array<main.FriendView>>;

export function Login(arg1:main.LoginInput):Promise<main.SessionInfo>;

export function Logout():Promise<void>;

export function RefreshToken():Promise<main.SessionInfo>;

export function Register(arg1:main.RegisterInput):Promise<main.RegisterResponse>;

export function RejectFriend(arg1:string):Promise<main.FriendView>;

export function RemoveGroupMember(arg1:string,arg2:string):Promise<void>;

export function RevokeGroupAdmin(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SearchUsers(arg1:string):Promise<Array<main.UserView>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.MessageView>;

export function SendReadReceipt(arg1:string,arg2:string):Promise<void>;

export function SendTyping(arg1:string):Promise<void>;

export function SwitchAccount(arg1:string):Promise<main.SessionInfo>;

export function TransferGroupOwner(arg1:string,arg2:string):Promise<main.ConversationView>;

export function UpdateGroupInfo(arg1:string,arg2:main.UpdateGroupInfoRequest):Promise<main.ConversationView>;

export function UploadAttachmentAndSend(arg1:string,arg2:string,arg3:string):Promise<main.MessageView>;
