// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: logic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckMessagePermissionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// message_type must be a short client-supported type such as text/image/file/voice/video.
	MessageType string `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// mentions is capped by the logic service before policy evaluation.
	Mentions      []int64 `protobuf:"varint,4,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMessagePermissionReq) Reset() {
	*x = CheckMessagePermissionReq{}
	mi := &file_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMessagePermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMessagePermissionReq) ProtoMessage() {}

func (x *CheckMessagePermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMessagePermissionReq.ProtoReflect.Descriptor instead.
func (*CheckMessagePermissionReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{0}
}

func (x *CheckMessagePermissionReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CheckMessagePermissionReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *CheckMessagePermissionReq) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CheckMessagePermissionReq) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type CheckMessagePermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	BizCode       int32                  `protobuf:"varint,2,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMessagePermissionResp) Reset() {
	*x = CheckMessagePermissionResp{}
	mi := &file_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMessagePermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMessagePermissionResp) ProtoMessage() {}

func (x *CheckMessagePermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMessagePermissionResp.ProtoReflect.Descriptor instead.
func (*CheckMessagePermissionResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{1}
}

func (x *CheckMessagePermissionResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckMessagePermissionResp) GetBizCode() int32 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *CheckMessagePermissionResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfoResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserInfoReq) Reset() {
	*x = CreateUserInfoReq{}
	mi := &file_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInfoReq) ProtoMessage() {}

func (x *CreateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInfoReq.ProtoReflect.Descriptor instead.
func (*CreateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserInfoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserInfoReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfoResponse      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserInfoResp) Reset() {
	*x = CreateUserInfoResp{}
	mi := &file_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInfoResp) ProtoMessage() {}

func (x *CreateUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInfoResp.ProtoReflect.Descriptor instead.
func (*CreateUserInfoResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserInfoResp) GetUser() *UserInfoResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_logic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserInfoByEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByEmailReq) Reset() {
	*x = GetUserInfoByEmailReq{}
	mi := &file_logic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByEmailReq) ProtoMessage() {}

func (x *GetUserInfoByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByEmailReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoByEmailReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserInfoByNicknameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByNicknameReq) Reset() {
	*x = GetUserInfoByNicknameReq{}
	mi := &file_logic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByNicknameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByNicknameReq) ProtoMessage() {}

func (x *GetUserInfoByNicknameReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByNicknameReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoByNicknameReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoByNicknameReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfoResponse      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_logic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResp) GetUser() *UserInfoResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoProfileReq) Reset() {
	*x = UpdateUserInfoProfileReq{}
	mi := &file_logic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoProfileReq) ProtoMessage() {}

func (x *UpdateUserInfoProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoProfileReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserInfoProfileReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserInfoProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserInfoProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserInfoProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfoResponse      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoProfileResp) Reset() {
	*x = UpdateUserInfoProfileResp{}
	mi := &file_logic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoProfileResp) ProtoMessage() {}

func (x *UpdateUserInfoProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoProfileResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserInfoProfileResp) GetUser() *UserInfoResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoStatusReq) Reset() {
	*x = UpdateUserInfoStatusReq{}
	mi := &file_logic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoStatusReq) ProtoMessage() {}

func (x *UpdateUserInfoStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoStatusReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserInfoStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserInfoStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateUserInfoStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfoResponse      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoStatusResp) Reset() {
	*x = UpdateUserInfoStatusResp{}
	mi := &file_logic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoStatusResp) ProtoMessage() {}

func (x *UpdateUserInfoStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoStatusResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserInfoStatusResp) GetUser() *UserInfoResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type SearchUserInfoByNicknameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserInfoByNicknameReq) Reset() {
	*x = SearchUserInfoByNicknameReq{}
	mi := &file_logic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserInfoByNicknameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserInfoByNicknameReq) ProtoMessage() {}

func (x *SearchUserInfoByNicknameReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserInfoByNicknameReq.ProtoReflect.Descriptor instead.
func (*SearchUserInfoByNicknameReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{13}
}

func (x *SearchUserInfoByNicknameReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SearchUserInfoByNicknameReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUserInfoByNicknameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfoResponse    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserInfoByNicknameResp) Reset() {
	*x = SearchUserInfoByNicknameResp{}
	mi := &file_logic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserInfoByNicknameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserInfoByNicknameResp) ProtoMessage() {}

func (x *SearchUserInfoByNicknameResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserInfoByNicknameResp.ProtoReflect.Descriptor instead.
func (*SearchUserInfoByNicknameResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{14}
}

func (x *SearchUserInfoByNicknameResp) GetUsers() []*UserInfoResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateConversationReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationType string                 `protobuf:"bytes,1,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"` // "direct" or "group"
	CreatorId        int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	MemberIds        []int64                `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateConversationReq) Reset() {
	*x = CreateConversationReq{}
	mi := &file_logic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationReq) ProtoMessage() {}

func (x *CreateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationReq.ProtoReflect.Descriptor instead.
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{15}
}

func (x *CreateConversationReq) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *CreateConversationReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateConversationReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type ConversationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationType string                 `protobuf:"bytes,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"`
	IsActive         bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp in milliseconds
	MemberIds        []int64                `protobuf:"varint,5,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_logic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{16}
}

func (x *ConversationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConversationResponse) GetConversationType() string {
	if x != nil {
		return x.ConversationType
	}
	return ""
}

func (x *ConversationResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ConversationResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConversationResponse) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *ConversationResponse  `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResp) Reset() {
	*x = CreateConversationResp{}
	mi := &file_logic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResp) ProtoMessage() {}

func (x *CreateConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResp.ProtoReflect.Descriptor instead.
func (*CreateConversationResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{17}
}

func (x *CreateConversationResp) GetConversation() *ConversationResponse {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type GetConversationMembersReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationMembersReq) Reset() {
	*x = GetConversationMembersReq{}
	mi := &file_logic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationMembersReq) ProtoMessage() {}

func (x *GetConversationMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationMembersReq.ProtoReflect.Descriptor instead.
func (*GetConversationMembersReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{18}
}

func (x *GetConversationMembersReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type GetConversationMembersResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MemberIds      []int64                `protobuf:"varint,2,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationMembersResp) Reset() {
	*x = GetConversationMembersResp{}
	mi := &file_logic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationMembersResp) ProtoMessage() {}

func (x *GetConversationMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationMembersResp.ProtoReflect.Descriptor instead.
func (*GetConversationMembersResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{19}
}

func (x *GetConversationMembersResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetConversationMembersResp) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type GetUserConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsReq) Reset() {
	*x = GetUserConversationsReq{}
	mi := &file_logic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsReq) ProtoMessage() {}

func (x *GetUserConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsReq.ProtoReflect.Descriptor instead.
func (*GetUserConversationsReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserConversationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserConversationsResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Conversations []*ConversationResponse `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsResp) Reset() {
	*x = GetUserConversationsResp{}
	mi := &file_logic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsResp) ProtoMessage() {}

func (x *GetUserConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsResp.ProtoReflect.Descriptor instead.
func (*GetUserConversationsResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserConversationsResp) GetConversations() []*ConversationResponse {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type GetConversationHistoryReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Cursor-based pagination: provide cursor_created_at and cursor_id for the next page.
	// If both are 0, returns the initial (latest) page.
	CursorCreatedAt int64 `protobuf:"varint,2,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"` // unix milliseconds of the last message's created_at
	CursorId        int64 `protobuf:"varint,3,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`                        // message ID cursor
	Limit           int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                              // max messages per page, default 50, max 100
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConversationHistoryReq) Reset() {
	*x = GetConversationHistoryReq{}
	mi := &file_logic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHistoryReq) ProtoMessage() {}

func (x *GetConversationHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHistoryReq.ProtoReflect.Descriptor instead.
func (*GetConversationHistoryReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{22}
}

func (x *GetConversationHistoryReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetConversationHistoryReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *GetConversationHistoryReq) GetCursorId() int64 {
	if x != nil {
		return x.CursorId
	}
	return 0
}

func (x *GetConversationHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessageItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageType    string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                              // JSON-encoded content
	ClientMsgId    string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // optional, may be empty
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // unix timestamp in milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_logic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{23}
}

func (x *MessageItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageItem) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MessageItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageItem) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetConversationHistoryResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Messages            []*MessageItem         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"` // 0 if no more pages
	NextCursorId        int64                  `protobuf:"varint,3,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`                        // 0 if no more pages
	HasMore             bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetConversationHistoryResp) Reset() {
	*x = GetConversationHistoryResp{}
	mi := &file_logic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHistoryResp) ProtoMessage() {}

func (x *GetConversationHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHistoryResp.ProtoReflect.Descriptor instead.
func (*GetConversationHistoryResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{24}
}

func (x *GetConversationHistoryResp) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetConversationHistoryResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *GetConversationHistoryResp) GetNextCursorId() int64 {
	if x != nil {
		return x.NextCursorId
	}
	return 0
}

func (x *GetConversationHistoryResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type AddFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // the requester's user id
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // the target user id to add as friend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendReq) Reset() {
	*x = AddFriendReq{}
	mi := &file_logic_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendReq) ProtoMessage() {}

func (x *AddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendReq.ProtoReflect.Descriptor instead.
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{25}
}

func (x *AddFriendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddFriendReq) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type FriendshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                         // "pending", "accepted", "blocked"
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp in milliseconds
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendshipResponse) Reset() {
	*x = FriendshipResponse{}
	mi := &file_logic_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipResponse) ProtoMessage() {}

func (x *FriendshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipResponse.ProtoReflect.Descriptor instead.
func (*FriendshipResponse) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{26}
}

func (x *FriendshipResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendshipResponse) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendshipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendshipResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FriendshipResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *FriendshipResponse    `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResp) Reset() {
	*x = AddFriendResp{}
	mi := &file_logic_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResp) ProtoMessage() {}

func (x *AddFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResp.ProtoReflect.Descriptor instead.
func (*AddFriendResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{27}
}

func (x *AddFriendResp) GetFriendship() *FriendshipResponse {
	if x != nil {
		return x.Friendship
	}
	return nil
}

type ListFriendApplicationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendApplicationsReq) Reset() {
	*x = ListFriendApplicationsReq{}
	mi := &file_logic_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendApplicationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendApplicationsReq) ProtoMessage() {}

func (x *ListFriendApplicationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendApplicationsReq.ProtoReflect.Descriptor instead.
func (*ListFriendApplicationsReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{28}
}

func (x *ListFriendApplicationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListFriendApplicationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*FriendshipResponse  `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendApplicationsResp) Reset() {
	*x = ListFriendApplicationsResp{}
	mi := &file_logic_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendApplicationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendApplicationsResp) ProtoMessage() {}

func (x *ListFriendApplicationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendApplicationsResp.ProtoReflect.Descriptor instead.
func (*ListFriendApplicationsResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{29}
}

func (x *ListFriendApplicationsResp) GetApplications() []*FriendshipResponse {
	if x != nil {
		return x.Applications
	}
	return nil
}

type AcceptFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // the user accepting the request
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // the original requester
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendReq) Reset() {
	*x = AcceptFriendReq{}
	mi := &file_logic_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendReq) ProtoMessage() {}

func (x *AcceptFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendReq.ProtoReflect.Descriptor instead.
func (*AcceptFriendReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{30}
}

func (x *AcceptFriendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AcceptFriendReq) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type AcceptFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *FriendshipResponse    `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResp) Reset() {
	*x = AcceptFriendResp{}
	mi := &file_logic_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResp) ProtoMessage() {}

func (x *AcceptFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResp.ProtoReflect.Descriptor instead.
func (*AcceptFriendResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{31}
}

func (x *AcceptFriendResp) GetFriendship() *FriendshipResponse {
	if x != nil {
		return x.Friendship
	}
	return nil
}

type RejectFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // the user rejecting the request
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // the original requester
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendReq) Reset() {
	*x = RejectFriendReq{}
	mi := &file_logic_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendReq) ProtoMessage() {}

func (x *RejectFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendReq.ProtoReflect.Descriptor instead.
func (*RejectFriendReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{32}
}

func (x *RejectFriendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RejectFriendReq) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type RejectFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friendship    *FriendshipResponse    `protobuf:"bytes,1,opt,name=friendship,proto3" json:"friendship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendResp) Reset() {
	*x = RejectFriendResp{}
	mi := &file_logic_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendResp) ProtoMessage() {}

func (x *RejectFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendResp.ProtoReflect.Descriptor instead.
func (*RejectFriendResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{33}
}

func (x *RejectFriendResp) GetFriendship() *FriendshipResponse {
	if x != nil {
		return x.Friendship
	}
	return nil
}

type ListFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsReq) Reset() {
	*x = ListFriendsReq{}
	mi := &file_logic_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsReq) ProtoMessage() {}

func (x *ListFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsReq.ProtoReflect.Descriptor instead.
func (*ListFriendsReq) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{34}
}

func (x *ListFriendsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendshipResponse  `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResp) Reset() {
	*x = ListFriendsResp{}
	mi := &file_logic_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResp) ProtoMessage() {}

func (x *ListFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResp.ProtoReflect.Descriptor instead.
func (*ListFriendsResp) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{35}
}

func (x *ListFriendsResp) GetFriends() []*FriendshipResponse {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_logic_proto protoreflect.FileDescriptor

const file_logic_proto_rawDesc = "" +
	"\n" +
	"\vlogic.proto\x12\x05logic\"\xa0\x01\n" +
	"\x19CheckMessagePermissionReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12\x1a\n" +
	"\bmentions\x18\x04 \x03(\x03R\bmentions\"i\n" +
	"\x1aCheckMessagePermissionResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x19\n" +
	"\bbiz_code\x18\x02 \x01(\x05R\abizCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xc2\x01\n" +
	"\x10UserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"m\n" +
	"\x11CreateUserInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"A\n" +
	"\x12CreateUserInfoResp\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.logic.UserInfoResponseR\x04user\" \n" +
	"\x0eGetUserInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x15GetUserInfoByEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"6\n" +
	"\x18GetUserInfoByNicknameReq\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\">\n" +
	"\x0fGetUserInfoResp\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.logic.UserInfoResponseR\x04user\"^\n" +
	"\x18UpdateUserInfoProfileReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"H\n" +
	"\x19UpdateUserInfoProfileResp\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.logic.UserInfoResponseR\x04user\"A\n" +
	"\x17UpdateUserInfoStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"G\n" +
	"\x18UpdateUserInfoStatusResp\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.logic.UserInfoResponseR\x04user\"O\n" +
	"\x1bSearchUserInfoByNicknameReq\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x1cSearchUserInfoByNicknameResp\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.logic.UserInfoResponseR\x05users\"\x82\x01\n" +
	"\x15CreateConversationReq\x12+\n" +
	"\x11conversation_type\x18\x01 \x01(\tR\x10conversationType\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03R\tmemberIds\"\xae\x01\n" +
	"\x14ConversationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\tR\x10conversationType\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\x03R\tmemberIds\"Y\n" +
	"\x16CreateConversationResp\x12?\n" +
	"\fconversation\x18\x01 \x01(\v2\x1b.logic.ConversationResponseR\fconversation\"D\n" +
	"\x19GetConversationMembersReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\"d\n" +
	"\x1aGetConversationMembersResp\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\x03R\tmemberIds\"2\n" +
	"\x17GetUserConversationsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"]\n" +
	"\x18GetUserConversationsResp\x12A\n" +
	"\rconversations\x18\x01 \x03(\v2\x1b.logic.ConversationResponseR\rconversations\"\xa3\x01\n" +
	"\x19GetConversationHistoryReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12*\n" +
	"\x11cursor_created_at\x18\x02 \x01(\x03R\x0fcursorCreatedAt\x12\x1b\n" +
	"\tcursor_id\x18\x03 \x01(\x03R\bcursorId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xe3\x01\n" +
	"\vMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xc2\x01\n" +
	"\x1aGetConversationHistoryResp\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.logic.MessageItemR\bmessages\x123\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03R\x13nextCursorCreatedAt\x12$\n" +
	"\x0enext_cursor_id\x18\x03 \x01(\x03R\fnextCursorId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"D\n" +
	"\fAddFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"\xa0\x01\n" +
	"\x12FriendshipResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"J\n" +
	"\rAddFriendResp\x129\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x19.logic.FriendshipResponseR\n" +
	"friendship\"4\n" +
	"\x19ListFriendApplicationsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"[\n" +
	"\x1aListFriendApplicationsResp\x12=\n" +
	"\fapplications\x18\x01 \x03(\v2\x19.logic.FriendshipResponseR\fapplications\"G\n" +
	"\x0fAcceptFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"M\n" +
	"\x10AcceptFriendResp\x129\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x19.logic.FriendshipResponseR\n" +
	"friendship\"G\n" +
	"\x0fRejectFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"M\n" +
	"\x10RejectFriendResp\x129\n" +
	"\n" +
	"friendship\x18\x01 \x01(\v2\x19.logic.FriendshipResponseR\n" +
	"friendship\")\n" +
	"\x0eListFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"F\n" +
	"\x0fListFriendsResp\x123\n" +
	"\afriends\x18\x01 \x03(\v2\x19.logic.FriendshipResponseR\afriends2r\n" +
	"\x11PermissionService\x12]\n" +
	"\x16CheckMessagePermission\x12 .logic.CheckMessagePermissionReq\x1a!.logic.CheckMessagePermissionResp2\xca\x04\n" +
	"\vUserService\x12E\n" +
	"\x0eCreateUserInfo\x12\x18.logic.CreateUserInfoReq\x1a\x19.logic.CreateUserInfoResp\x12<\n" +
	"\vGetUserInfo\x12\x15.logic.GetUserInfoReq\x1a\x16.logic.GetUserInfoResp\x12J\n" +
	"\x12GetUserInfoByEmail\x12\x1c.logic.GetUserInfoByEmailReq\x1a\x16.logic.GetUserInfoResp\x12P\n" +
	"\x15GetUserInfoByNickname\x12\x1f.logic.GetUserInfoByNicknameReq\x1a\x16.logic.GetUserInfoResp\x12Z\n" +
	"\x15UpdateUserInfoProfile\x12\x1f.logic.UpdateUserInfoProfileReq\x1a .logic.UpdateUserInfoProfileResp\x12W\n" +
	"\x14UpdateUserInfoStatus\x12\x1e.logic.UpdateUserInfoStatusReq\x1a\x1f.logic.UpdateUserInfoStatusResp\x12c\n" +
	"\x18SearchUserInfoByNickname\x12\".logic.SearchUserInfoByNicknameReq\x1a#.logic.SearchUserInfoByNicknameResp2\xff\x02\n" +
	"\x13ConversationService\x12Q\n" +
	"\x12CreateConversation\x12\x1c.logic.CreateConversationReq\x1a\x1d.logic.CreateConversationResp\x12]\n" +
	"\x16GetConversationHistory\x12 .logic.GetConversationHistoryReq\x1a!.logic.GetConversationHistoryResp\x12]\n" +
	"\x16GetConversationMembers\x12 .logic.GetConversationMembersReq\x1a!.logic.GetConversationMembersResp\x12W\n" +
	"\x14GetUserConversations\x12\x1e.logic.GetUserConversationsReq\x1a\x1f.logic.GetUserConversationsResp2\xea\x02\n" +
	"\x11FriendshipService\x126\n" +
	"\tAddFriend\x12\x13.logic.AddFriendReq\x1a\x14.logic.AddFriendResp\x12]\n" +
	"\x16ListFriendApplications\x12 .logic.ListFriendApplicationsReq\x1a!.logic.ListFriendApplicationsResp\x12?\n" +
	"\fAcceptFriend\x12\x16.logic.AcceptFriendReq\x1a\x17.logic.AcceptFriendResp\x12?\n" +
	"\fRejectFriend\x12\x16.logic.RejectFriendReq\x1a\x17.logic.RejectFriendResp\x12<\n" +
	"\vListFriends\x12\x15.logic.ListFriendsReq\x1a\x16.logic.ListFriendsRespB\x06Z\x04./pbb\x06proto3"

var (
	file_logic_proto_rawDescOnce sync.Once
	file_logic_proto_rawDescData []byte
)

func file_logic_proto_rawDescGZIP() []byte {
	file_logic_proto_rawDescOnce.Do(func() {
		file_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)))
	})
	return file_logic_proto_rawDescData
}

var file_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_logic_proto_goTypes = []any{
	(*CheckMessagePermissionReq)(nil),    // 0: logic.CheckMessagePermissionReq
	(*CheckMessagePermissionResp)(nil),   // 1: logic.CheckMessagePermissionResp
	(*UserInfoResponse)(nil),             // 2: logic.UserInfoResponse
	(*CreateUserInfoReq)(nil),            // 3: logic.CreateUserInfoReq
	(*CreateUserInfoResp)(nil),           // 4: logic.CreateUserInfoResp
	(*GetUserInfoReq)(nil),               // 5: logic.GetUserInfoReq
	(*GetUserInfoByEmailReq)(nil),        // 6: logic.GetUserInfoByEmailReq
	(*GetUserInfoByNicknameReq)(nil),     // 7: logic.GetUserInfoByNicknameReq
	(*GetUserInfoResp)(nil),              // 8: logic.GetUserInfoResp
	(*UpdateUserInfoProfileReq)(nil),     // 9: logic.UpdateUserInfoProfileReq
	(*UpdateUserInfoProfileResp)(nil),    // 10: logic.UpdateUserInfoProfileResp
	(*UpdateUserInfoStatusReq)(nil),      // 11: logic.UpdateUserInfoStatusReq
	(*UpdateUserInfoStatusResp)(nil),     // 12: logic.UpdateUserInfoStatusResp
	(*SearchUserInfoByNicknameReq)(nil),  // 13: logic.SearchUserInfoByNicknameReq
	(*SearchUserInfoByNicknameResp)(nil), // 14: logic.SearchUserInfoByNicknameResp
	(*CreateConversationReq)(nil),        // 15: logic.CreateConversationReq
	(*ConversationResponse)(nil),         // 16: logic.ConversationResponse
	(*CreateConversationResp)(nil),       // 17: logic.CreateConversationResp
	(*GetConversationMembersReq)(nil),    // 18: logic.GetConversationMembersReq
	(*GetConversationMembersResp)(nil),   // 19: logic.GetConversationMembersResp
	(*GetUserConversationsReq)(nil),      // 20: logic.GetUserConversationsReq
	(*GetUserConversationsResp)(nil),     // 21: logic.GetUserConversationsResp
	(*GetConversationHistoryReq)(nil),    // 22: logic.GetConversationHistoryReq
	(*MessageItem)(nil),                  // 23: logic.MessageItem
	(*GetConversationHistoryResp)(nil),   // 24: logic.GetConversationHistoryResp
	(*AddFriendReq)(nil),                 // 25: logic.AddFriendReq
	(*FriendshipResponse)(nil),           // 26: logic.FriendshipResponse
	(*AddFriendResp)(nil),                // 27: logic.AddFriendResp
	(*ListFriendApplicationsReq)(nil),    // 28: logic.ListFriendApplicationsReq
	(*ListFriendApplicationsResp)(nil),   // 29: logic.ListFriendApplicationsResp
	(*AcceptFriendReq)(nil),              // 30: logic.AcceptFriendReq
	(*AcceptFriendResp)(nil),             // 31: logic.AcceptFriendResp
	(*RejectFriendReq)(nil),              // 32: logic.RejectFriendReq
	(*RejectFriendResp)(nil),             // 33: logic.RejectFriendResp
	(*ListFriendsReq)(nil),               // 34: logic.ListFriendsReq
	(*ListFriendsResp)(nil),              // 35: logic.ListFriendsResp
}
var file_logic_proto_depIdxs = []int32{
	2,  // 0: logic.CreateUserInfoResp.user:type_name -> logic.UserInfoResponse
	2,  // 1: logic.GetUserInfoResp.user:type_name -> logic.UserInfoResponse
	2,  // 2: logic.UpdateUserInfoProfileResp.user:type_name -> logic.UserInfoResponse
	2,  // 3: logic.UpdateUserInfoStatusResp.user:type_name -> logic.UserInfoResponse
	2,  // 4: logic.SearchUserInfoByNicknameResp.users:type_name -> logic.UserInfoResponse
	16, // 5: logic.CreateConversationResp.conversation:type_name -> logic.ConversationResponse
	16, // 6: logic.GetUserConversationsResp.conversations:type_name -> logic.ConversationResponse
	23, // 7: logic.GetConversationHistoryResp.messages:type_name -> logic.MessageItem
	26, // 8: logic.AddFriendResp.friendship:type_name -> logic.FriendshipResponse
	26, // 9: logic.ListFriendApplicationsResp.applications:type_name -> logic.FriendshipResponse
	26, // 10: logic.AcceptFriendResp.friendship:type_name -> logic.FriendshipResponse
	26, // 11: logic.RejectFriendResp.friendship:type_name -> logic.FriendshipResponse
	26, // 12: logic.ListFriendsResp.friends:type_name -> logic.FriendshipResponse
	0,  // 13: logic.PermissionService.CheckMessagePermission:input_type -> logic.CheckMessagePermissionReq
	3,  // 14: logic.UserService.CreateUserInfo:input_type -> logic.CreateUserInfoReq
	5,  // 15: logic.UserService.GetUserInfo:input_type -> logic.GetUserInfoReq
	6,  // 16: logic.UserService.GetUserInfoByEmail:input_type -> logic.GetUserInfoByEmailReq
	7,  // 17: logic.UserService.GetUserInfoByNickname:input_type -> logic.GetUserInfoByNicknameReq
	9,  // 18: logic.UserService.UpdateUserInfoProfile:input_type -> logic.UpdateUserInfoProfileReq
	11, // 19: logic.UserService.UpdateUserInfoStatus:input_type -> logic.UpdateUserInfoStatusReq
	13, // 20: logic.UserService.SearchUserInfoByNickname:input_type -> logic.SearchUserInfoByNicknameReq
	15, // 21: logic.ConversationService.CreateConversation:input_type -> logic.CreateConversationReq
	22, // 22: logic.ConversationService.GetConversationHistory:input_type -> logic.GetConversationHistoryReq
	18, // 23: logic.ConversationService.GetConversationMembers:input_type -> logic.GetConversationMembersReq
	20, // 24: logic.ConversationService.GetUserConversations:input_type -> logic.GetUserConversationsReq
	25, // 25: logic.FriendshipService.AddFriend:input_type -> logic.AddFriendReq
	28, // 26: logic.FriendshipService.ListFriendApplications:input_type -> logic.ListFriendApplicationsReq
	30, // 27: logic.FriendshipService.AcceptFriend:input_type -> logic.AcceptFriendReq
	32, // 28: logic.FriendshipService.RejectFriend:input_type -> logic.RejectFriendReq
	34, // 29: logic.FriendshipService.ListFriends:input_type -> logic.ListFriendsReq
	1,  // 30: logic.PermissionService.CheckMessagePermission:output_type -> logic.CheckMessagePermissionResp
	4,  // 31: logic.UserService.CreateUserInfo:output_type -> logic.CreateUserInfoResp
	8,  // 32: logic.UserService.GetUserInfo:output_type -> logic.GetUserInfoResp
	8,  // 33: logic.UserService.GetUserInfoByEmail:output_type -> logic.GetUserInfoResp
	8,  // 34: logic.UserService.GetUserInfoByNickname:output_type -> logic.GetUserInfoResp
	10, // 35: logic.UserService.UpdateUserInfoProfile:output_type -> logic.UpdateUserInfoProfileResp
	12, // 36: logic.UserService.UpdateUserInfoStatus:output_type -> logic.UpdateUserInfoStatusResp
	14, // 37: logic.UserService.SearchUserInfoByNickname:output_type -> logic.SearchUserInfoByNicknameResp
	17, // 38: logic.ConversationService.CreateConversation:output_type -> logic.CreateConversationResp
	24, // 39: logic.ConversationService.GetConversationHistory:output_type -> logic.GetConversationHistoryResp
	19, // 40: logic.ConversationService.GetConversationMembers:output_type -> logic.GetConversationMembersResp
	21, // 41: logic.ConversationService.GetUserConversations:output_type -> logic.GetUserConversationsResp
	27, // 42: logic.FriendshipService.AddFriend:output_type -> logic.AddFriendResp
	29, // 43: logic.FriendshipService.ListFriendApplications:output_type -> logic.ListFriendApplicationsResp
	31, // 44: logic.FriendshipService.AcceptFriend:output_type -> logic.AcceptFriendResp
	33, // 45: logic.FriendshipService.RejectFriend:output_type -> logic.RejectFriendResp
	35, // 46: logic.FriendshipService.ListFriends:output_type -> logic.ListFriendsResp
	30, // [30:47] is the sub-list for method output_type
	13, // [13:30] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_logic_proto_init() }
func file_logic_proto_init() {
	if File_logic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logic_proto_rawDesc), len(file_logic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_logic_proto_goTypes,
		DependencyIndexes: file_logic_proto_depIdxs,
		MessageInfos:      file_logic_proto_msgTypes,
	}.Build()
	File_logic_proto = out.File
	file_logic_proto_goTypes = nil
	file_logic_proto_depIdxs = nil
}
