// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package server

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/internal/logic"
	"github.com/hellopoisonx/aim/app/logic/rpc/internal/svc"
	"github.com/hellopoisonx/aim/app/logic/rpc/pb"
)

type PermissionServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPermissionServiceServer
}

func NewPermissionServiceServer(svcCtx *svc.ServiceContext) *PermissionServiceServer {
	return &PermissionServiceServer{
		svcCtx: svcCtx,
	}
}

// CheckMessagePermission checks whether a sender can publish into a conversation.
func (s *PermissionServiceServer) CheckMessagePermission(ctx context.Context, in *pb.CheckMessagePermissionReq) (*pb.CheckMessagePermissionResp, error) {
	l := logic.NewCheckMessagePermissionLogic(ctx, s.svcCtx)
	return l.CheckMessagePermission(in)
}
