// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AcceptFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type AcceptFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type AddFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type AddFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type CreateConversationRequest struct {
	ConversationType string  `json:"conversation_type" validate:"required,oneof=direct group"`
	MemberIds        []int64 `json:"member_ids" validate:"required,min=1"`
}

type CreateConversationResponse struct {
	ConversationId   int64   `json:"conversation_id"`
	ConversationType string  `json:"conversation_type"`
	IsActive         bool    `json:"is_active"`
	CreatedAt        int64   `json:"created_at"`
	MemberIds        []int64 `json:"member_ids"`
}

type FriendshipItem struct {
	UserId    int64  `json:"user_id"`
	FriendId  int64  `json:"friend_id"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type GetConversationHistoryRequest struct {
	Id              int64 `path:"id" validate:"required"`
	CursorCreatedAt int64 `form:"cursor_created_at,optional"`
	CursorId        int64 `form:"cursor_id,optional"`
	Limit           int32 `form:"limit,default=50,optional"`
}

type GetConversationHistoryResponse struct {
	Messages            []MessageItem `json:"messages"`
	NextCursorCreatedAt int64         `json:"next_cursor_created_at"`
	NextCursorId        int64         `json:"next_cursor_id"`
	HasMore             bool          `json:"has_more"`
}

type GetUserByIdRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type GetUserByIdResponse struct {
	User UserInfo `json:"user"`
}

type GetUserByNameRequest struct {
	Name string `path:"name" validate:"required"`
}

type GetUserByNameResponse struct {
	Users []UserListItem `json:"users"`
}

type ListFriendApplicationsResponse struct {
	Applications []FriendshipItem `json:"applications"`
}

type ListFriendsResponse struct {
	Friends []FriendshipItem `json:"friends"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8"`
	DeviceId string `json:"device_id" validate:"required"`
}

type LoginResponse struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type MessageItem struct {
	Id             int64  `json:"id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	MessageType    string `json:"message_type"`
	Content        string `json:"content"`
	ClientMsgId    string `json:"client_msg_id"`
	CreatedAt      int64  `json:"created_at"`
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RefreshResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8"`
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
	DeviceId string `json:"device_id" validate:"required"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
}

type RejectFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type RejectFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Email     string `json:"email"`
	Status    int32  `json:"status"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserListItem struct {
	Id     int64  `json:"id"`
	Email  string `json:"email"`
	Avatar string `json:"avatar"`
}
