// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AcceptFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type AcceptFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type AddFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type AddFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type AddGroupMembersRequest struct {
	Id        int64   `path:"id" validate:"required"`
	MemberIds []int64 `json:"member_ids" validate:"required,min=1"`
}

type AddGroupMembersResponse struct {
	ConversationId   int64   `json:"conversation_id"`
	ConversationType string  `json:"conversation_type"`
	IsActive         bool    `json:"is_active"`
	CreatedAt        int64   `json:"created_at"`
	MemberIds        []int64 `json:"member_ids"`
	Name             string  `json:"name"`
	Avatar           string  `json:"avatar"`
	CreatorId        int64   `json:"creator_id"`
	DisplayName      string  `json:"display_name,optional"`
}

type AttachmentFileInfo struct {
	FileId             string                 `json:"file_id"`
	OwnerId            int64                  `json:"owner_id"`
	ConversationId     int64                  `json:"conversation_id"`
	Kind               string                 `json:"kind"`
	OriginalName       string                 `json:"original_name"`
	Mime               string                 `json:"mime"`
	Size               int64                  `json:"size"`
	Sha256             string                 `json:"sha256,optional"`
	Status             string                 `json:"status"`
	ParseStatus        string                 `json:"parse_status"`
	Bucket             string                 `json:"bucket"`
	ObjectKey          string                 `json:"object_key"`
	ThumbnailObjectKey string                 `json:"thumbnail_object_key,optional"`
	DurationMs         int64                  `json:"duration_ms,optional"`
	Width              int32                  `json:"width,optional"`
	Height             int32                  `json:"height,optional"`
	Metadata           map[string]interface{} `json:"metadata,optional"`
}

type BotConversationItem struct {
	ConversationId   string `json:"conversation_id"`
	ConversationType string `json:"conversation_type"`
	Name             string `json:"name"`
	Avatar           string `json:"avatar"`
	CreatedAt        int64  `json:"created_at"`
}

type BotDeleteWebhookResponse struct {
	Deleted bool `json:"deleted"`
}

type BotDownloadAttachmentRequest struct {
	Id string `path:"id" validate:"required"`
}

type BotDownloadAttachmentResponse struct {
	Url       string            `json:"url"`
	Headers   map[string]string `json:"headers,optional"`
	ExpiresAt int64             `json:"expires_at"`
}

type BotGetWebhookResponse struct {
	Configured bool             `json:"configured"`
	Webhook    BotWebhookConfig `json:"webhook"`
}

type BotListConversationsResponse struct {
	Conversations []BotConversationItem `json:"conversations"`
}

type BotMe struct {
	BotUserId string   `json:"bot_user_id"`
	Nickname  string   `json:"nickname"`
	Avatar    string   `json:"avatar"`
	Status    int32    `json:"status"`
	Scopes    []string `json:"scopes"`
}

type BotMeResponse struct {
	Bot BotMe `json:"bot"`
}

type BotSendMessageRequest struct {
	ConversationId string   `json:"conversation_id" validate:"required"`
	MessageType    string   `json:"message_type" validate:"required,max=32"`
	Content        string   `json:"content" validate:"required"`
	ClientMsgId    string   `json:"client_msg_id" validate:"required"`
	Mentions       []string `json:"mentions,optional"`
}

type BotSendMessageResponse struct {
	MessageId   string `json:"message_id"`
	ClientMsgId string `json:"client_msg_id"`
	AcceptedAt  int64  `json:"accepted_at"`
}

type BotSetWebhookRequest struct {
	Url          string   `json:"url" validate:"required,url"`
	Events       []string `json:"events,optional"`
	Enabled      *bool    `json:"enabled,optional"`
	Secret       string   `json:"secret,optional"`
	RotateSecret bool     `json:"rotate_secret,optional"`
}

type BotSetWebhookResponse struct {
	Webhook         BotWebhookConfig `json:"webhook"`
	PlaintextSecret string           `json:"plaintext_secret,omitempty"`
}

type BotWebhookConfig struct {
	Url       string   `json:"url"`
	Events    []string `json:"events"`
	Enabled   bool     `json:"enabled"`
	UpdatedAt int64    `json:"updated_at"`
}

type CompleteAttachmentUploadRequest struct {
	Id     string `path:"id" validate:"required"`
	Sha256 string `json:"sha256,optional"`
}

type ConversationItem struct {
	ConversationId   int64   `json:"conversation_id"`
	ConversationType string  `json:"conversation_type"`
	IsActive         bool    `json:"is_active"`
	CreatedAt        int64   `json:"created_at"`
	MemberIds        []int64 `json:"member_ids"`
	Name             string  `json:"name"`
	Avatar           string  `json:"avatar"`
	CreatorId        int64   `json:"creator_id"`
	DisplayName      string  `json:"display_name,optional"`
}

type CreateConversationRequest struct {
	ConversationType string  `json:"conversation_type" validate:"required,oneof=direct group"`
	MemberIds        []int64 `json:"member_ids" validate:"required,min=1"`
	Name             string  `json:"name,optional"`
	Avatar           string  `json:"avatar,optional"`
}

type CreateConversationResponse struct {
	ConversationId   int64   `json:"conversation_id"`
	ConversationType string  `json:"conversation_type"`
	IsActive         bool    `json:"is_active"`
	CreatedAt        int64   `json:"created_at"`
	MemberIds        []int64 `json:"member_ids"`
	Name             string  `json:"name"`
	Avatar           string  `json:"avatar"`
	CreatorId        int64   `json:"creator_id"`
	DisplayName      string  `json:"display_name,optional"`
}

type CreateGroupRequest struct {
	MemberIds []int64 `json:"member_ids" validate:"required,min=1"`
	Name      string  `json:"name" validate:"required"`
	Avatar    string  `json:"avatar,optional"`
}

type DismissGroupRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type DownloadAttachmentRequest struct {
	Id string `path:"id" validate:"required"`
}

type DownloadAttachmentResponse struct {
	Url       string            `json:"url"`
	Headers   map[string]string `json:"headers,optional"`
	ExpiresAt int64             `json:"expires_at"`
}

type FriendshipItem struct {
	UserId      int64  `json:"user_id"`
	FriendId    int64  `json:"friend_id"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DisplayName string `json:"display_name,optional"`
	Email       string `json:"email,optional"`
	Avatar      string `json:"avatar,optional"`
}

type GetAttachmentRequest struct {
	Id string `path:"id" validate:"required"`
}

type GetConversationHistoryRequest struct {
	Id              int64 `path:"id" validate:"required"`
	CursorCreatedAt int64 `form:"cursor_created_at,optional"`
	CursorId        int64 `form:"cursor_id,optional"`
	Limit           int32 `form:"limit,default=50,optional"`
}

type GetConversationHistoryResponse struct {
	Messages            []MessageItem   `json:"messages"`
	NextCursorCreatedAt int64           `json:"next_cursor_created_at"`
	NextCursorId        int64           `json:"next_cursor_id"`
	HasMore             bool            `json:"has_more"`
	ReadStates          []ReadStateItem `json:"read_states"`
}

type GetConversationMembersDetailRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type GetConversationMembersResponse struct {
	Members []MemberDetailItem `json:"members"`
}

type GetFriendsPresenceResponse struct {
	Presences []PresenceItem `json:"presences"`
}

type GetUserByIdRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type GetUserByIdResponse struct {
	User UserInfo `json:"user"`
}

type GetUserByNameRequest struct {
	Name string `path:"name" validate:"required"`
}

type GetUserByNameResponse struct {
	Users []UserListItem `json:"users"`
}

type GrantGroupAdminRequest struct {
	Id  int64 `path:"id" validate:"required"`
	Uid int64 `path:"uid" validate:"required"`
}

type InitAttachmentUploadRequest struct {
	ConversationId int64  `json:"conversation_id" validate:"required"`
	Kind           string `json:"kind" validate:"required,oneof=image video audio file"`
	OriginalName   string `json:"original_name" validate:"required"`
	Mime           string `json:"mime" validate:"required"`
	Size           int64  `json:"size" validate:"required"`
	Sha256         string `json:"sha256,optional"`
}

type InitAttachmentUploadResponse struct {
	FileId       string            `json:"file_id"`
	Bucket       string            `json:"bucket"`
	ObjectKey    string            `json:"object_key"`
	UploadUrl    string            `json:"upload_url"`
	UploadMethod string            `json:"upload_method"`
	Headers      map[string]string `json:"headers,optional"`
	ExpiresAt    int64             `json:"expires_at"`
}

type LeaveGroupRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type ListConversationsResponse struct {
	Conversations []ConversationItem `json:"conversations"`
}

type ListFriendApplicationsResponse struct {
	Applications []FriendshipItem `json:"applications"`
}

type ListFriendsResponse struct {
	Friends []FriendshipItem `json:"friends"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8"`
	DeviceId string `json:"device_id" validate:"required"`
}

type LoginResponse struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type MemberDetailItem struct {
	UserId      int64  `json:"user_id"`
	Email       string `json:"email"`
	Avatar      string `json:"avatar"`
	Role        string `json:"role"`
	JoinedAt    int64  `json:"joined_at"`
	DisplayName string `json:"display_name,optional"`
}

type MessageItem struct {
	Id             int64                   `json:"id"`
	ConversationId int64                   `json:"conversation_id"`
	SenderId       int64                   `json:"sender_id"`
	SenderInfo     SenderInfo              `json:"sender_info"`
	MessageType    string                  `json:"message_type"`
	Content        string                  `json:"content"`
	ClientMsgId    string                  `json:"client_msg_id"`
	CreatedAt      int64                   `json:"created_at"`
	IsSystem       bool                    `json:"is_system,optional"`
	Mentions       []string                `json:"mentions,optional"`
	ReadDetails    []MessageReadDetailItem `json:"read_details"`
}

type MessageReadDetailItem struct {
	UserId            int64  `json:"user_id"`
	IsRead            bool   `json:"is_read"`
	LastReadMessageId int64  `json:"last_read_message_id"`
	UpdatedAt         int64  `json:"updated_at"`
	Email             string `json:"email"`
	Avatar            string `json:"avatar"`
	DisplayName       string `json:"display_name,optional"`
}

type PresenceItem struct {
	UserId      int64  `json:"user_id"`
	Status      string `json:"status"`
	UpdatedAt   int64  `json:"updated_at"`
	DisplayName string `json:"display_name,optional"`
}

type ReadStateItem struct {
	UserId            int64  `json:"user_id"`
	LastReadMessageId int64  `json:"last_read_message_id"`
	UpdatedAt         int64  `json:"updated_at"`
	Email             string `json:"email,optional"`
	Avatar            string `json:"avatar,optional"`
	DisplayName       string `json:"display_name,optional"`
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RefreshResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8"`
	Username string `json:"username" validate:"required"`
	Avatar   string `json:"avatar,optional"`
	DeviceId string `json:"device_id" validate:"required"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
}

type RejectFriendRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type RejectFriendResponse struct {
	Friendship FriendshipItem `json:"friendship"`
}

type RemoveGroupMemberRequest struct {
	Id  int64 `path:"id" validate:"required"`
	Uid int64 `path:"uid" validate:"required"`
}

type RevokeGroupAdminRequest struct {
	Id  int64 `path:"id" validate:"required"`
	Uid int64 `path:"uid" validate:"required"`
}

type SenderInfo struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name,optional"`
}

type TransferGroupOwnerRequest struct {
	Id     int64 `path:"id" validate:"required"`
	UserId int64 `json:"user_id" validate:"required"`
}

type TransferGroupOwnerResponse struct {
	ConversationId   int64   `json:"conversation_id"`
	ConversationType string  `json:"conversation_type"`
	IsActive         bool    `json:"is_active"`
	CreatedAt        int64   `json:"created_at"`
	MemberIds        []int64 `json:"member_ids"`
	Name             string  `json:"name"`
	Avatar           string  `json:"avatar"`
	CreatorId        int64   `json:"creator_id"`
	DisplayName      string  `json:"display_name,optional"`
}

type UpdateGroupInfoRequest struct {
	Id     int64   `path:"id" validate:"required"`
	Name   *string `json:"name,optional"`
	Avatar *string `json:"avatar,optional"`
}

type UpdateGroupInfoResponse struct {
	ConversationId   int64  `json:"conversation_id"`
	ConversationType string `json:"conversation_type"`
	IsActive         bool   `json:"is_active"`
	Name             string `json:"name"`
	Avatar           string `json:"avatar"`
	CreatorId        int64  `json:"creator_id"`
	CreatedAt        int64  `json:"created_at"`
}

type UserInfo struct {
	Id          int64  `json:"id"`
	Email       string `json:"email"`
	Status      int32  `json:"status"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	DisplayName string `json:"display_name,optional"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type UserListItem struct {
	Id          string `json:"id"`
	Nickname    string `json:"nickname"`
	Email       string `json:"email"`
	Avatar      string `json:"avatar"`
	DisplayName string `json:"display_name,optional"`
}
