/**
 * Local TypeScript interfaces for AIM desktop chat workspace components.
 * These are decoupled from Wails generated types — components never call
 * Go bindings directly; they receive data via props and emit events.
 *
 * NOTE: These types should match the wails-generated types from ../wailsjs/go/models
 */

export interface Conversation {
  id: string
  title: string
  avatar?: string
  lastMessage?: string
  lastMessageAt?: string
  unreadCount: number
  isOnline: boolean
  conversationType?: 'direct' | 'group'
  creatorId?: string
  memberIds?: string[]
  /** 历史消息游标分页信息 */
  historyCursor?: {
    cursorCreatedAt: number
    cursorId: string
    hasMore: boolean
  }
}

export interface ChatMessage {
  id: string
  conversationId: string
  senderId: string
  senderName: string
  senderAvatar?: string
  content: string
  timestamp: string
  isMine: boolean
  isSystem?: boolean
  clientMsgId?: string
  ackStatus?: 'pending' | 'delivered' | 'failed'
}

/** Group member detail from server */
export interface GroupMemberItem {
  userId: string
  email: string
  avatar: string
  role: string
  joinedAt: number
}

/** Search user result item, derived from client.UserListItem */
export interface SearchUserItem {
  id: string
  email: string
  avatar?: string
}

/** Friend request / application from server */
export interface FriendRequest {
  id: string
  userId: string
  friendId: string
  status: string
  createdAt: number
  updatedAt: number
  userEmail?: string
}

/** Friend item (accepted friend) */
export interface FriendItem {
  id: string
  userId: string
  friendId: string
  email: string
  avatar: string
  isOnline: boolean
}

// ============================================
// Vueapi types - helpers for converting client types
// These are NOT auto-generated by Wails, so we define them here
// ============================================

export namespace vueapi {
  export interface SessionState {
    UserID: string
    AccessToken: string
    RefreshToken: string
    ExpiresAt: number
    ws_connected: boolean
  }

  export interface MessageItem {
    id: string
    conversation_id: string
    sender_id: string
    message_type: string
    content: string
    client_msg_id: string
    created_at: number
  }

  export interface UserInfo {
    id: string
    nickname: string
    email: string
    avatar: string
  }

  export interface ConversationItem {
    conversation_id: string
    conversation_type: string
    is_active: boolean
    created_at: number
    member_ids: string[]
    name: string
    avatar: string
    creator_id: string
  }
}
