// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: attachment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitUploadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	OriginalName   string                 `protobuf:"bytes,4,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Mime           string                 `protobuf:"bytes,5,opt,name=mime,proto3" json:"mime,omitempty"`
	Size           int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Sha256         string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitUploadReq) Reset() {
	*x = InitUploadReq{}
	mi := &file_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadReq) ProtoMessage() {}

func (x *InitUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadReq.ProtoReflect.Descriptor instead.
func (*InitUploadReq) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *InitUploadReq) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *InitUploadReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *InitUploadReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InitUploadReq) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *InitUploadReq) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *InitUploadReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitUploadReq) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type InitUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,4,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	UploadMethod  string                 `protobuf:"bytes,5,opt,name=upload_method,json=uploadMethod,proto3" json:"upload_method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadResp) Reset() {
	*x = InitUploadResp{}
	mi := &file_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadResp) ProtoMessage() {}

func (x *InitUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadResp.ProtoReflect.Descriptor instead.
func (*InitUploadResp) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *InitUploadResp) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *InitUploadResp) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *InitUploadResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *InitUploadResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitUploadResp) GetUploadMethod() string {
	if x != nil {
		return x.UploadMethod
	}
	return ""
}

func (x *InitUploadResp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InitUploadResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CompleteUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadReq) Reset() {
	*x = CompleteUploadReq{}
	mi := &file_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadReq) ProtoMessage() {}

func (x *CompleteUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteUploadReq) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompleteUploadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CompleteUploadReq) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileReq) Reset() {
	*x = GetFileReq{}
	mi := &file_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReq) ProtoMessage() {}

func (x *GetFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReq.ProtoReflect.Descriptor instead.
func (*GetFileReq) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFileReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type AuthorizeDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeDownloadReq) Reset() {
	*x = AuthorizeDownloadReq{}
	mi := &file_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeDownloadReq) ProtoMessage() {}

func (x *AuthorizeDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeDownloadReq.ProtoReflect.Descriptor instead.
func (*AuthorizeDownloadReq) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeDownloadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizeDownloadReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type AuthorizeDownloadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeDownloadResp) Reset() {
	*x = AuthorizeDownloadResp{}
	mi := &file_attachment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeDownloadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeDownloadResp) ProtoMessage() {}

func (x *AuthorizeDownloadResp) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeDownloadResp.ProtoReflect.Descriptor instead.
func (*AuthorizeDownloadResp) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizeDownloadResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AuthorizeDownloadResp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AuthorizeDownloadResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ValidateReferenceReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FileId         string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Kind           string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateReferenceReq) Reset() {
	*x = ValidateReferenceReq{}
	mi := &file_attachment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReferenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReferenceReq) ProtoMessage() {}

func (x *ValidateReferenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReferenceReq.ProtoReflect.Descriptor instead.
func (*ValidateReferenceReq) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateReferenceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateReferenceReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ValidateReferenceReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ValidateReferenceReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type FileInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FileId             string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId            int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ConversationId     int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Kind               string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	OriginalName       string                 `protobuf:"bytes,5,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Mime               string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	Size               int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Sha256             string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Status             string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ParseStatus        string                 `protobuf:"bytes,10,opt,name=parse_status,json=parseStatus,proto3" json:"parse_status,omitempty"`
	Bucket             string                 `protobuf:"bytes,11,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey          string                 `protobuf:"bytes,12,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ThumbnailObjectKey string                 `protobuf:"bytes,13,opt,name=thumbnail_object_key,json=thumbnailObjectKey,proto3" json:"thumbnail_object_key,omitempty"`
	DurationMs         int64                  `protobuf:"varint,14,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Width              int32                  `protobuf:"varint,15,opt,name=width,proto3" json:"width,omitempty"`
	Height             int32                  `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	MetadataJson       string                 `protobuf:"bytes,17,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_attachment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *FileInfo) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *FileInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FileInfo) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileInfo) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileInfo) GetParseStatus() string {
	if x != nil {
		return x.ParseStatus
	}
	return ""
}

func (x *FileInfo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileInfo) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *FileInfo) GetThumbnailObjectKey() string {
	if x != nil {
		return x.ThumbnailObjectKey
	}
	return ""
}

func (x *FileInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *FileInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FileInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FileInfo) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

var File_attachment_proto protoreflect.FileDescriptor

const file_attachment_proto_rawDesc = "" +
	"\n" +
	"\x10attachment.proto\x12\n" +
	"attachment\"\xcc\x01\n" +
	"\rInitUploadReq\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12#\n" +
	"\roriginal_name\x18\x04 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04mime\x18\x05 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\"\xc2\x02\n" +
	"\x0eInitUploadResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x04 \x01(\tR\tuploadUrl\x12#\n" +
	"\rupload_method\x18\x05 \x01(\tR\fuploadMethod\x12A\n" +
	"\aheaders\x18\x06 \x03(\v2'.attachment.InitUploadResp.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x11CompleteUploadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\">\n" +
	"\n" +
	"GetFileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"H\n" +
	"\x14AuthorizeDownloadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\xce\x01\n" +
	"\x15AuthorizeDownloadResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12H\n" +
	"\aheaders\x18\x02 \x03(\v2..attachment.AuthorizeDownloadResp.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x14ValidateReferenceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"\xf8\x03\n" +
	"\bFileInfo\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12#\n" +
	"\roriginal_name\x18\x05 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12!\n" +
	"\fparse_status\x18\n" +
	" \x01(\tR\vparseStatus\x12\x16\n" +
	"\x06bucket\x18\v \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\f \x01(\tR\tobjectKey\x120\n" +
	"\x14thumbnail_object_key\x18\r \x01(\tR\x12thumbnailObjectKey\x12\x1f\n" +
	"\vduration_ms\x18\x0e \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05width\x18\x0f \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x05R\x06height\x12#\n" +
	"\rmetadata_json\x18\x11 \x01(\tR\fmetadataJson2\xff\x02\n" +
	"\x11AttachmentService\x12C\n" +
	"\n" +
	"InitUpload\x12\x19.attachment.InitUploadReq\x1a\x1a.attachment.InitUploadResp\x12E\n" +
	"\x0eCompleteUpload\x12\x1d.attachment.CompleteUploadReq\x1a\x14.attachment.FileInfo\x127\n" +
	"\aGetFile\x12\x16.attachment.GetFileReq\x1a\x14.attachment.FileInfo\x12X\n" +
	"\x11AuthorizeDownload\x12 .attachment.AuthorizeDownloadReq\x1a!.attachment.AuthorizeDownloadResp\x12K\n" +
	"\x11ValidateReference\x12 .attachment.ValidateReferenceReq\x1a\x14.attachment.FileInfoB\x06Z\x04./pbb\x06proto3"

var (
	file_attachment_proto_rawDescOnce sync.Once
	file_attachment_proto_rawDescData []byte
)

func file_attachment_proto_rawDescGZIP() []byte {
	file_attachment_proto_rawDescOnce.Do(func() {
		file_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)))
	})
	return file_attachment_proto_rawDescData
}

var file_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_attachment_proto_goTypes = []any{
	(*InitUploadReq)(nil),         // 0: attachment.InitUploadReq
	(*InitUploadResp)(nil),        // 1: attachment.InitUploadResp
	(*CompleteUploadReq)(nil),     // 2: attachment.CompleteUploadReq
	(*GetFileReq)(nil),            // 3: attachment.GetFileReq
	(*AuthorizeDownloadReq)(nil),  // 4: attachment.AuthorizeDownloadReq
	(*AuthorizeDownloadResp)(nil), // 5: attachment.AuthorizeDownloadResp
	(*ValidateReferenceReq)(nil),  // 6: attachment.ValidateReferenceReq
	(*FileInfo)(nil),              // 7: attachment.FileInfo
	nil,                           // 8: attachment.InitUploadResp.HeadersEntry
	nil,                           // 9: attachment.AuthorizeDownloadResp.HeadersEntry
}
var file_attachment_proto_depIdxs = []int32{
	8, // 0: attachment.InitUploadResp.headers:type_name -> attachment.InitUploadResp.HeadersEntry
	9, // 1: attachment.AuthorizeDownloadResp.headers:type_name -> attachment.AuthorizeDownloadResp.HeadersEntry
	0, // 2: attachment.AttachmentService.InitUpload:input_type -> attachment.InitUploadReq
	2, // 3: attachment.AttachmentService.CompleteUpload:input_type -> attachment.CompleteUploadReq
	3, // 4: attachment.AttachmentService.GetFile:input_type -> attachment.GetFileReq
	4, // 5: attachment.AttachmentService.AuthorizeDownload:input_type -> attachment.AuthorizeDownloadReq
	6, // 6: attachment.AttachmentService.ValidateReference:input_type -> attachment.ValidateReferenceReq
	1, // 7: attachment.AttachmentService.InitUpload:output_type -> attachment.InitUploadResp
	7, // 8: attachment.AttachmentService.CompleteUpload:output_type -> attachment.FileInfo
	7, // 9: attachment.AttachmentService.GetFile:output_type -> attachment.FileInfo
	5, // 10: attachment.AttachmentService.AuthorizeDownload:output_type -> attachment.AuthorizeDownloadResp
	7, // 11: attachment.AttachmentService.ValidateReference:output_type -> attachment.FileInfo
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_attachment_proto_init() }
func file_attachment_proto_init() {
	if File_attachment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attachment_proto_goTypes,
		DependencyIndexes: file_attachment_proto_depIdxs,
		MessageInfos:      file_attachment_proto_msgTypes,
	}.Build()
	File_attachment_proto = out.File
	file_attachment_proto_goTypes = nil
	file_attachment_proto_depIdxs = nil
}
