// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package model

import (
	"context"
)

const getConversation = `-- name: GetConversation :one
SELECT id, conversation_type, is_active
FROM conversations
WHERE id = $1
`

type GetConversationRow struct {
	ID               int64  `json:"id"`
	ConversationType string `json:"conversation_type"`
	IsActive         bool   `json:"is_active"`
}

func (q *Queries) GetConversation(ctx context.Context, id int64) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i GetConversationRow
	err := row.Scan(&i.ID, &i.ConversationType, &i.IsActive)
	return i, err
}
