// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMember = `-- name: GetMember :one
SELECT conversation_id, user_id, is_muted, muted_until
FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

type GetMemberRow struct {
	ConversationID int64              `json:"conversation_id"`
	UserID         int64              `json:"user_id"`
	IsMuted        bool               `json:"is_muted"`
	MutedUntil     pgtype.Timestamptz `json:"muted_until"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ConversationID, arg.UserID)
	var i GetMemberRow
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.IsMuted,
		&i.MutedUntil,
	)
	return i, err
}

const isMemberMuted = `-- name: IsMemberMuted :one
SELECT is_muted, muted_until
FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type IsMemberMutedParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

type IsMemberMutedRow struct {
	IsMuted    bool               `json:"is_muted"`
	MutedUntil pgtype.Timestamptz `json:"muted_until"`
}

func (q *Queries) IsMemberMuted(ctx context.Context, arg IsMemberMutedParams) (IsMemberMutedRow, error) {
	row := q.db.QueryRow(ctx, isMemberMuted, arg.ConversationID, arg.UserID)
	var i IsMemberMutedRow
	err := row.Scan(&i.IsMuted, &i.MutedUntil)
	return i, err
}
