// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package model

import (
	"context"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, conversation_id, sender_id, message_type, content, client_msg_id, mentions, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type InsertMessageParams struct {
	ID             int64   `json:"id"`
	ConversationID int64   `json:"conversation_id"`
	SenderID       int64   `json:"sender_id"`
	MessageType    string  `json:"message_type"`
	Content        []byte  `json:"content"`
	ClientMsgID    *string `json:"client_msg_id"`
	Mentions       []byte  `json:"mentions"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.MessageType,
		arg.Content,
		arg.ClientMsgID,
		arg.Mentions,
	)
	return err
}
