// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID               int64              `json:"id"`
	ConversationType string             `json:"conversation_type"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ConversationMember struct {
	ConversationID int64              `json:"conversation_id"`
	UserID         int64              `json:"user_id"`
	IsMuted        bool               `json:"is_muted"`
	MutedUntil     pgtype.Timestamptz `json:"muted_until"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type Friendship struct {
	UserID    int64              `json:"user_id"`
	FriendID  int64              `json:"friend_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
