// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"context"
)

type Querier interface {
	GetConversation(ctx context.Context, id int64) (GetConversationRow, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (GetFriendshipRow, error)
	GetFriendshipBidirectional(ctx context.Context, arg GetFriendshipBidirectionalParams) ([]GetFriendshipBidirectionalRow, error)
	GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	IsMemberMuted(ctx context.Context, arg IsMemberMutedParams) (IsMemberMutedRow, error)
}

var _ Querier = (*Queries)(nil)
