// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logic.proto

package friendshipservice

import (
	"context"

	"github.com/hellopoisonx/aim/app/logic/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptFriendReq            = pb.AcceptFriendReq
	AcceptFriendResp           = pb.AcceptFriendResp
	AddFriendReq               = pb.AddFriendReq
	AddFriendResp              = pb.AddFriendResp
	ListFriendApplicationsReq  = pb.ListFriendApplicationsReq
	ListFriendApplicationsResp = pb.ListFriendApplicationsResp
	RejectFriendReq            = pb.RejectFriendReq
	RejectFriendResp           = pb.RejectFriendResp

	FriendshipService interface {
		// AddFriend sends a friend request or accepts an existing pending one.
		AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error)
		// ListFriendApplications lists pending friend applications received by the user.
		ListFriendApplications(ctx context.Context, in *ListFriendApplicationsReq, opts ...grpc.CallOption) (*ListFriendApplicationsResp, error)
		// AcceptFriend accepts a pending friend request.
		AcceptFriend(ctx context.Context, in *AcceptFriendReq, opts ...grpc.CallOption) (*AcceptFriendResp, error)
		// RejectFriend rejects a pending friend request.
		RejectFriend(ctx context.Context, in *RejectFriendReq, opts ...grpc.CallOption) (*RejectFriendResp, error)
	}

	defaultFriendshipService struct {
		cli zrpc.Client
	}
)

func NewFriendshipService(cli zrpc.Client) FriendshipService {
	return &defaultFriendshipService{
		cli: cli,
	}
}

// AddFriend sends a friend request or accepts an existing pending one.
func (m *defaultFriendshipService) AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error) {
	client := pb.NewFriendshipServiceClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

// ListFriendApplications lists pending friend applications received by the user.
func (m *defaultFriendshipService) ListFriendApplications(ctx context.Context, in *ListFriendApplicationsReq, opts ...grpc.CallOption) (*ListFriendApplicationsResp, error) {
	client := pb.NewFriendshipServiceClient(m.cli.Conn())
	return client.ListFriendApplications(ctx, in, opts...)
}

// AcceptFriend accepts a pending friend request.
func (m *defaultFriendshipService) AcceptFriend(ctx context.Context, in *AcceptFriendReq, opts ...grpc.CallOption) (*AcceptFriendResp, error) {
	client := pb.NewFriendshipServiceClient(m.cli.Conn())
	return client.AcceptFriend(ctx, in, opts...)
}

// RejectFriend rejects a pending friend request.
func (m *defaultFriendshipService) RejectFriend(ctx context.Context, in *RejectFriendReq, opts ...grpc.CallOption) (*RejectFriendResp, error) {
	client := pb.NewFriendshipServiceClient(m.cli.Conn())
	return client.RejectFriend(ctx, in, opts...)
}
